// Code generated by ent, DO NOT EDIT.

package copilotplatformconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlanType applies equality check predicate on the "plan_type" field. It's identical to PlanTypeEQ.
func PlanType(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldPlanType, v))
}

// MaxOutputTokens applies equality check predicate on the "max_output_tokens" field. It's identical to MaxOutputTokensEQ.
func MaxOutputTokens(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldMaxOutputTokens, v))
}

// MaxBodyKB applies equality check predicate on the "max_body_kb" field. It's identical to MaxBodyKBEQ.
func MaxBodyKB(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldMaxBodyKB, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// PlanTypeEQ applies the EQ predicate on the "plan_type" field.
func PlanTypeEQ(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldPlanType, v))
}

// PlanTypeNEQ applies the NEQ predicate on the "plan_type" field.
func PlanTypeNEQ(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldPlanType, v))
}

// PlanTypeIn applies the In predicate on the "plan_type" field.
func PlanTypeIn(vs ...string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldPlanType, vs...))
}

// PlanTypeNotIn applies the NotIn predicate on the "plan_type" field.
func PlanTypeNotIn(vs ...string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldPlanType, vs...))
}

// PlanTypeGT applies the GT predicate on the "plan_type" field.
func PlanTypeGT(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldPlanType, v))
}

// PlanTypeGTE applies the GTE predicate on the "plan_type" field.
func PlanTypeGTE(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldPlanType, v))
}

// PlanTypeLT applies the LT predicate on the "plan_type" field.
func PlanTypeLT(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldPlanType, v))
}

// PlanTypeLTE applies the LTE predicate on the "plan_type" field.
func PlanTypeLTE(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldPlanType, v))
}

// PlanTypeContains applies the Contains predicate on the "plan_type" field.
func PlanTypeContains(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldContains(FieldPlanType, v))
}

// PlanTypeHasPrefix applies the HasPrefix predicate on the "plan_type" field.
func PlanTypeHasPrefix(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldHasPrefix(FieldPlanType, v))
}

// PlanTypeHasSuffix applies the HasSuffix predicate on the "plan_type" field.
func PlanTypeHasSuffix(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldHasSuffix(FieldPlanType, v))
}

// PlanTypeEqualFold applies the EqualFold predicate on the "plan_type" field.
func PlanTypeEqualFold(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEqualFold(FieldPlanType, v))
}

// PlanTypeContainsFold applies the ContainsFold predicate on the "plan_type" field.
func PlanTypeContainsFold(v string) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldContainsFold(FieldPlanType, v))
}

// MaxOutputTokensEQ applies the EQ predicate on the "max_output_tokens" field.
func MaxOutputTokensEQ(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldMaxOutputTokens, v))
}

// MaxOutputTokensNEQ applies the NEQ predicate on the "max_output_tokens" field.
func MaxOutputTokensNEQ(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldMaxOutputTokens, v))
}

// MaxOutputTokensIn applies the In predicate on the "max_output_tokens" field.
func MaxOutputTokensIn(vs ...int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldMaxOutputTokens, vs...))
}

// MaxOutputTokensNotIn applies the NotIn predicate on the "max_output_tokens" field.
func MaxOutputTokensNotIn(vs ...int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldMaxOutputTokens, vs...))
}

// MaxOutputTokensGT applies the GT predicate on the "max_output_tokens" field.
func MaxOutputTokensGT(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldMaxOutputTokens, v))
}

// MaxOutputTokensGTE applies the GTE predicate on the "max_output_tokens" field.
func MaxOutputTokensGTE(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldMaxOutputTokens, v))
}

// MaxOutputTokensLT applies the LT predicate on the "max_output_tokens" field.
func MaxOutputTokensLT(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldMaxOutputTokens, v))
}

// MaxOutputTokensLTE applies the LTE predicate on the "max_output_tokens" field.
func MaxOutputTokensLTE(v int64) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldMaxOutputTokens, v))
}

// MaxOutputTokensIsNil applies the IsNil predicate on the "max_output_tokens" field.
func MaxOutputTokensIsNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIsNull(FieldMaxOutputTokens))
}

// MaxOutputTokensNotNil applies the NotNil predicate on the "max_output_tokens" field.
func MaxOutputTokensNotNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotNull(FieldMaxOutputTokens))
}

// MaxBodyKBEQ applies the EQ predicate on the "max_body_kb" field.
func MaxBodyKBEQ(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldEQ(FieldMaxBodyKB, v))
}

// MaxBodyKBNEQ applies the NEQ predicate on the "max_body_kb" field.
func MaxBodyKBNEQ(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNEQ(FieldMaxBodyKB, v))
}

// MaxBodyKBIn applies the In predicate on the "max_body_kb" field.
func MaxBodyKBIn(vs ...int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIn(FieldMaxBodyKB, vs...))
}

// MaxBodyKBNotIn applies the NotIn predicate on the "max_body_kb" field.
func MaxBodyKBNotIn(vs ...int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotIn(FieldMaxBodyKB, vs...))
}

// MaxBodyKBGT applies the GT predicate on the "max_body_kb" field.
func MaxBodyKBGT(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGT(FieldMaxBodyKB, v))
}

// MaxBodyKBGTE applies the GTE predicate on the "max_body_kb" field.
func MaxBodyKBGTE(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldGTE(FieldMaxBodyKB, v))
}

// MaxBodyKBLT applies the LT predicate on the "max_body_kb" field.
func MaxBodyKBLT(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLT(FieldMaxBodyKB, v))
}

// MaxBodyKBLTE applies the LTE predicate on the "max_body_kb" field.
func MaxBodyKBLTE(v int) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldLTE(FieldMaxBodyKB, v))
}

// MaxBodyKBIsNil applies the IsNil predicate on the "max_body_kb" field.
func MaxBodyKBIsNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIsNull(FieldMaxBodyKB))
}

// MaxBodyKBNotNil applies the NotNil predicate on the "max_body_kb" field.
func MaxBodyKBNotNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotNull(FieldMaxBodyKB))
}

// ModelMappingIsNil applies the IsNil predicate on the "model_mapping" field.
func ModelMappingIsNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIsNull(FieldModelMapping))
}

// ModelMappingNotNil applies the NotNil predicate on the "model_mapping" field.
func ModelMappingNotNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotNull(FieldModelMapping))
}

// ModelWhitelistIsNil applies the IsNil predicate on the "model_whitelist" field.
func ModelWhitelistIsNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldIsNull(FieldModelWhitelist))
}

// ModelWhitelistNotNil applies the NotNil predicate on the "model_whitelist" field.
func ModelWhitelistNotNil() predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.FieldNotNull(FieldModelWhitelist))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CopilotPlatformConfig) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CopilotPlatformConfig) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CopilotPlatformConfig) predicate.CopilotPlatformConfig {
	return predicate.CopilotPlatformConfig(sql.NotPredicates(p))
}
