// Code generated by ent, DO NOT EDIT.

package paymentcallback

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldOrderNo, v))
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldPaymentMethod, v))
}

// TransactionID applies equality check predicate on the "transaction_id" field. It's identical to TransactionIDEQ.
func TransactionID(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldTransactionID, v))
}

// RequestHeaders applies equality check predicate on the "request_headers" field. It's identical to RequestHeadersEQ.
func RequestHeaders(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldRequestBody, v))
}

// SignatureValid applies equality check predicate on the "signature_valid" field. It's identical to SignatureValidEQ.
func SignatureValid(v bool) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldSignatureValid, v))
}

// ProcessStatus applies equality check predicate on the "process_status" field. It's identical to ProcessStatusEQ.
func ProcessStatus(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessStatus, v))
}

// ProcessMessage applies equality check predicate on the "process_message" field. It's identical to ProcessMessageEQ.
func ProcessMessage(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessMessage, v))
}

// ResponseCode applies equality check predicate on the "response_code" field. It's identical to ResponseCodeEQ.
func ResponseCode(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldResponseCode, v))
}

// ResponseMessage applies equality check predicate on the "response_message" field. It's identical to ResponseMessageEQ.
func ResponseMessage(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldResponseMessage, v))
}

// ProcessTimeMs applies equality check predicate on the "process_time_ms" field. It's identical to ProcessTimeMsEQ.
func ProcessTimeMs(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessTimeMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoIsNil applies the IsNil predicate on the "order_no" field.
func OrderNoIsNil() predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIsNull(FieldOrderNo))
}

// OrderNoNotNil applies the NotNil predicate on the "order_no" field.
func OrderNoNotNil() predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotNull(FieldOrderNo))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldOrderNo, v))
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldPaymentMethod, v))
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldPaymentMethod, v))
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldPaymentMethod, vs...))
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldPaymentMethod, vs...))
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldPaymentMethod, v))
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldPaymentMethod, v))
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldPaymentMethod, v))
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldPaymentMethod, v))
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldPaymentMethod, v))
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldPaymentMethod, v))
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldPaymentMethod, v))
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldPaymentMethod, v))
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldPaymentMethod, v))
}

// TransactionIDEQ applies the EQ predicate on the "transaction_id" field.
func TransactionIDEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldTransactionID, v))
}

// TransactionIDNEQ applies the NEQ predicate on the "transaction_id" field.
func TransactionIDNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldTransactionID, v))
}

// TransactionIDIn applies the In predicate on the "transaction_id" field.
func TransactionIDIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldTransactionID, vs...))
}

// TransactionIDNotIn applies the NotIn predicate on the "transaction_id" field.
func TransactionIDNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldTransactionID, vs...))
}

// TransactionIDGT applies the GT predicate on the "transaction_id" field.
func TransactionIDGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldTransactionID, v))
}

// TransactionIDGTE applies the GTE predicate on the "transaction_id" field.
func TransactionIDGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldTransactionID, v))
}

// TransactionIDLT applies the LT predicate on the "transaction_id" field.
func TransactionIDLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldTransactionID, v))
}

// TransactionIDLTE applies the LTE predicate on the "transaction_id" field.
func TransactionIDLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldTransactionID, v))
}

// TransactionIDContains applies the Contains predicate on the "transaction_id" field.
func TransactionIDContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldTransactionID, v))
}

// TransactionIDHasPrefix applies the HasPrefix predicate on the "transaction_id" field.
func TransactionIDHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldTransactionID, v))
}

// TransactionIDHasSuffix applies the HasSuffix predicate on the "transaction_id" field.
func TransactionIDHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldTransactionID, v))
}

// TransactionIDIsNil applies the IsNil predicate on the "transaction_id" field.
func TransactionIDIsNil() predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIsNull(FieldTransactionID))
}

// TransactionIDNotNil applies the NotNil predicate on the "transaction_id" field.
func TransactionIDNotNil() predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotNull(FieldTransactionID))
}

// TransactionIDEqualFold applies the EqualFold predicate on the "transaction_id" field.
func TransactionIDEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldTransactionID, v))
}

// TransactionIDContainsFold applies the ContainsFold predicate on the "transaction_id" field.
func TransactionIDContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldTransactionID, v))
}

// RequestHeadersEQ applies the EQ predicate on the "request_headers" field.
func RequestHeadersEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldRequestHeaders, v))
}

// RequestHeadersNEQ applies the NEQ predicate on the "request_headers" field.
func RequestHeadersNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldRequestHeaders, v))
}

// RequestHeadersIn applies the In predicate on the "request_headers" field.
func RequestHeadersIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldRequestHeaders, vs...))
}

// RequestHeadersNotIn applies the NotIn predicate on the "request_headers" field.
func RequestHeadersNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldRequestHeaders, vs...))
}

// RequestHeadersGT applies the GT predicate on the "request_headers" field.
func RequestHeadersGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldRequestHeaders, v))
}

// RequestHeadersGTE applies the GTE predicate on the "request_headers" field.
func RequestHeadersGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldRequestHeaders, v))
}

// RequestHeadersLT applies the LT predicate on the "request_headers" field.
func RequestHeadersLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldRequestHeaders, v))
}

// RequestHeadersLTE applies the LTE predicate on the "request_headers" field.
func RequestHeadersLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldRequestHeaders, v))
}

// RequestHeadersContains applies the Contains predicate on the "request_headers" field.
func RequestHeadersContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldRequestHeaders, v))
}

// RequestHeadersHasPrefix applies the HasPrefix predicate on the "request_headers" field.
func RequestHeadersHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldRequestHeaders, v))
}

// RequestHeadersHasSuffix applies the HasSuffix predicate on the "request_headers" field.
func RequestHeadersHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldRequestHeaders, v))
}

// RequestHeadersEqualFold applies the EqualFold predicate on the "request_headers" field.
func RequestHeadersEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldRequestHeaders, v))
}

// RequestHeadersContainsFold applies the ContainsFold predicate on the "request_headers" field.
func RequestHeadersContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldRequestHeaders, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldRequestBody, v))
}

// SignatureValidEQ applies the EQ predicate on the "signature_valid" field.
func SignatureValidEQ(v bool) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldSignatureValid, v))
}

// SignatureValidNEQ applies the NEQ predicate on the "signature_valid" field.
func SignatureValidNEQ(v bool) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldSignatureValid, v))
}

// ProcessStatusEQ applies the EQ predicate on the "process_status" field.
func ProcessStatusEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessStatus, v))
}

// ProcessStatusNEQ applies the NEQ predicate on the "process_status" field.
func ProcessStatusNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldProcessStatus, v))
}

// ProcessStatusIn applies the In predicate on the "process_status" field.
func ProcessStatusIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldProcessStatus, vs...))
}

// ProcessStatusNotIn applies the NotIn predicate on the "process_status" field.
func ProcessStatusNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldProcessStatus, vs...))
}

// ProcessStatusGT applies the GT predicate on the "process_status" field.
func ProcessStatusGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldProcessStatus, v))
}

// ProcessStatusGTE applies the GTE predicate on the "process_status" field.
func ProcessStatusGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldProcessStatus, v))
}

// ProcessStatusLT applies the LT predicate on the "process_status" field.
func ProcessStatusLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldProcessStatus, v))
}

// ProcessStatusLTE applies the LTE predicate on the "process_status" field.
func ProcessStatusLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldProcessStatus, v))
}

// ProcessStatusContains applies the Contains predicate on the "process_status" field.
func ProcessStatusContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldProcessStatus, v))
}

// ProcessStatusHasPrefix applies the HasPrefix predicate on the "process_status" field.
func ProcessStatusHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldProcessStatus, v))
}

// ProcessStatusHasSuffix applies the HasSuffix predicate on the "process_status" field.
func ProcessStatusHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldProcessStatus, v))
}

// ProcessStatusEqualFold applies the EqualFold predicate on the "process_status" field.
func ProcessStatusEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldProcessStatus, v))
}

// ProcessStatusContainsFold applies the ContainsFold predicate on the "process_status" field.
func ProcessStatusContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldProcessStatus, v))
}

// ProcessMessageEQ applies the EQ predicate on the "process_message" field.
func ProcessMessageEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessMessage, v))
}

// ProcessMessageNEQ applies the NEQ predicate on the "process_message" field.
func ProcessMessageNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldProcessMessage, v))
}

// ProcessMessageIn applies the In predicate on the "process_message" field.
func ProcessMessageIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldProcessMessage, vs...))
}

// ProcessMessageNotIn applies the NotIn predicate on the "process_message" field.
func ProcessMessageNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldProcessMessage, vs...))
}

// ProcessMessageGT applies the GT predicate on the "process_message" field.
func ProcessMessageGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldProcessMessage, v))
}

// ProcessMessageGTE applies the GTE predicate on the "process_message" field.
func ProcessMessageGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldProcessMessage, v))
}

// ProcessMessageLT applies the LT predicate on the "process_message" field.
func ProcessMessageLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldProcessMessage, v))
}

// ProcessMessageLTE applies the LTE predicate on the "process_message" field.
func ProcessMessageLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldProcessMessage, v))
}

// ProcessMessageContains applies the Contains predicate on the "process_message" field.
func ProcessMessageContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldProcessMessage, v))
}

// ProcessMessageHasPrefix applies the HasPrefix predicate on the "process_message" field.
func ProcessMessageHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldProcessMessage, v))
}

// ProcessMessageHasSuffix applies the HasSuffix predicate on the "process_message" field.
func ProcessMessageHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldProcessMessage, v))
}

// ProcessMessageEqualFold applies the EqualFold predicate on the "process_message" field.
func ProcessMessageEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldProcessMessage, v))
}

// ProcessMessageContainsFold applies the ContainsFold predicate on the "process_message" field.
func ProcessMessageContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldProcessMessage, v))
}

// ResponseCodeEQ applies the EQ predicate on the "response_code" field.
func ResponseCodeEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldResponseCode, v))
}

// ResponseCodeNEQ applies the NEQ predicate on the "response_code" field.
func ResponseCodeNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldResponseCode, v))
}

// ResponseCodeIn applies the In predicate on the "response_code" field.
func ResponseCodeIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldResponseCode, vs...))
}

// ResponseCodeNotIn applies the NotIn predicate on the "response_code" field.
func ResponseCodeNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldResponseCode, vs...))
}

// ResponseCodeGT applies the GT predicate on the "response_code" field.
func ResponseCodeGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldResponseCode, v))
}

// ResponseCodeGTE applies the GTE predicate on the "response_code" field.
func ResponseCodeGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldResponseCode, v))
}

// ResponseCodeLT applies the LT predicate on the "response_code" field.
func ResponseCodeLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldResponseCode, v))
}

// ResponseCodeLTE applies the LTE predicate on the "response_code" field.
func ResponseCodeLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldResponseCode, v))
}

// ResponseCodeContains applies the Contains predicate on the "response_code" field.
func ResponseCodeContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldResponseCode, v))
}

// ResponseCodeHasPrefix applies the HasPrefix predicate on the "response_code" field.
func ResponseCodeHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldResponseCode, v))
}

// ResponseCodeHasSuffix applies the HasSuffix predicate on the "response_code" field.
func ResponseCodeHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldResponseCode, v))
}

// ResponseCodeEqualFold applies the EqualFold predicate on the "response_code" field.
func ResponseCodeEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldResponseCode, v))
}

// ResponseCodeContainsFold applies the ContainsFold predicate on the "response_code" field.
func ResponseCodeContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldResponseCode, v))
}

// ResponseMessageEQ applies the EQ predicate on the "response_message" field.
func ResponseMessageEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldResponseMessage, v))
}

// ResponseMessageNEQ applies the NEQ predicate on the "response_message" field.
func ResponseMessageNEQ(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldResponseMessage, v))
}

// ResponseMessageIn applies the In predicate on the "response_message" field.
func ResponseMessageIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldResponseMessage, vs...))
}

// ResponseMessageNotIn applies the NotIn predicate on the "response_message" field.
func ResponseMessageNotIn(vs ...string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldResponseMessage, vs...))
}

// ResponseMessageGT applies the GT predicate on the "response_message" field.
func ResponseMessageGT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldResponseMessage, v))
}

// ResponseMessageGTE applies the GTE predicate on the "response_message" field.
func ResponseMessageGTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldResponseMessage, v))
}

// ResponseMessageLT applies the LT predicate on the "response_message" field.
func ResponseMessageLT(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldResponseMessage, v))
}

// ResponseMessageLTE applies the LTE predicate on the "response_message" field.
func ResponseMessageLTE(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldResponseMessage, v))
}

// ResponseMessageContains applies the Contains predicate on the "response_message" field.
func ResponseMessageContains(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContains(FieldResponseMessage, v))
}

// ResponseMessageHasPrefix applies the HasPrefix predicate on the "response_message" field.
func ResponseMessageHasPrefix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasPrefix(FieldResponseMessage, v))
}

// ResponseMessageHasSuffix applies the HasSuffix predicate on the "response_message" field.
func ResponseMessageHasSuffix(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldHasSuffix(FieldResponseMessage, v))
}

// ResponseMessageEqualFold applies the EqualFold predicate on the "response_message" field.
func ResponseMessageEqualFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEqualFold(FieldResponseMessage, v))
}

// ResponseMessageContainsFold applies the ContainsFold predicate on the "response_message" field.
func ResponseMessageContainsFold(v string) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldContainsFold(FieldResponseMessage, v))
}

// ProcessTimeMsEQ applies the EQ predicate on the "process_time_ms" field.
func ProcessTimeMsEQ(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldEQ(FieldProcessTimeMs, v))
}

// ProcessTimeMsNEQ applies the NEQ predicate on the "process_time_ms" field.
func ProcessTimeMsNEQ(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNEQ(FieldProcessTimeMs, v))
}

// ProcessTimeMsIn applies the In predicate on the "process_time_ms" field.
func ProcessTimeMsIn(vs ...int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldIn(FieldProcessTimeMs, vs...))
}

// ProcessTimeMsNotIn applies the NotIn predicate on the "process_time_ms" field.
func ProcessTimeMsNotIn(vs ...int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldNotIn(FieldProcessTimeMs, vs...))
}

// ProcessTimeMsGT applies the GT predicate on the "process_time_ms" field.
func ProcessTimeMsGT(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGT(FieldProcessTimeMs, v))
}

// ProcessTimeMsGTE applies the GTE predicate on the "process_time_ms" field.
func ProcessTimeMsGTE(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldGTE(FieldProcessTimeMs, v))
}

// ProcessTimeMsLT applies the LT predicate on the "process_time_ms" field.
func ProcessTimeMsLT(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLT(FieldProcessTimeMs, v))
}

// ProcessTimeMsLTE applies the LTE predicate on the "process_time_ms" field.
func ProcessTimeMsLTE(v int64) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.FieldLTE(FieldProcessTimeMs, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentCallback) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentCallback) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentCallback) predicate.PaymentCallback {
	return predicate.PaymentCallback(sql.NotPredicates(p))
}
