// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancelot"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// BalanceLotUpdate is the builder for updating BalanceLot entities.
type BalanceLotUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceLotMutation
}

// Where appends a list predicates to the BalanceLotUpdate builder.
func (_u *BalanceLotUpdate) Where(ps ...predicate.BalanceLot) *BalanceLotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLotUpdate) SetUpdatedAt(v time.Time) *BalanceLotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLotUpdate) SetUserID(v int64) *BalanceLotUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableUserID(v *int64) *BalanceLotUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *BalanceLotUpdate) SetSourceType(v string) *BalanceLotUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableSourceType(v *string) *BalanceLotUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *BalanceLotUpdate) SetSourceRef(v string) *BalanceLotUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableSourceRef(v *string) *BalanceLotUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *BalanceLotUpdate) ClearSourceRef() *BalanceLotUpdate {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetOriginalAmount sets the "original_amount" field.
func (_u *BalanceLotUpdate) SetOriginalAmount(v float64) *BalanceLotUpdate {
	_u.mutation.ResetOriginalAmount()
	_u.mutation.SetOriginalAmount(v)
	return _u
}

// SetNillableOriginalAmount sets the "original_amount" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableOriginalAmount(v *float64) *BalanceLotUpdate {
	if v != nil {
		_u.SetOriginalAmount(*v)
	}
	return _u
}

// AddOriginalAmount adds value to the "original_amount" field.
func (_u *BalanceLotUpdate) AddOriginalAmount(v float64) *BalanceLotUpdate {
	_u.mutation.AddOriginalAmount(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *BalanceLotUpdate) SetRemainingAmount(v float64) *BalanceLotUpdate {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableRemainingAmount(v *float64) *BalanceLotUpdate {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *BalanceLotUpdate) AddRemainingAmount(v float64) *BalanceLotUpdate {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceLotUpdate) SetStatus(v string) *BalanceLotUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableStatus(v *string) *BalanceLotUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BalanceLotUpdate) SetExpiresAt(v time.Time) *BalanceLotUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableExpiresAt(v *time.Time) *BalanceLotUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *BalanceLotUpdate) SetExpiredAt(v time.Time) *BalanceLotUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableExpiredAt(v *time.Time) *BalanceLotUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *BalanceLotUpdate) ClearExpiredAt() *BalanceLotUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLotUpdate) SetDescription(v string) *BalanceLotUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLotUpdate) SetNillableDescription(v *string) *BalanceLotUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BalanceLotUpdate) SetUser(v *User) *BalanceLotUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BalanceLotMutation object of the builder.
func (_u *BalanceLotUpdate) Mutation() *BalanceLotMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BalanceLotUpdate) ClearUser() *BalanceLotUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceLotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceLotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancelot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLotUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := balancelot.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := balancelot.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRef(); ok {
		if err := balancelot.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.source_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancelot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceLot.user"`)
	}
	return nil
}

func (_u *BalanceLotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelot.Table, balancelot.Columns, sqlgraph.NewFieldSpec(balancelot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancelot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(balancelot.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(balancelot.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(balancelot.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalAmount(); ok {
		_spec.SetField(balancelot.FieldOriginalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalAmount(); ok {
		_spec.AddField(balancelot.FieldOriginalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(balancelot.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(balancelot.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancelot.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(balancelot.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(balancelot.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(balancelot.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancelot.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelot.UserTable,
			Columns: []string{balancelot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelot.UserTable,
			Columns: []string{balancelot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceLotUpdateOne is the builder for updating a single BalanceLot entity.
type BalanceLotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceLotMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLotUpdateOne) SetUpdatedAt(v time.Time) *BalanceLotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLotUpdateOne) SetUserID(v int64) *BalanceLotUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableUserID(v *int64) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *BalanceLotUpdateOne) SetSourceType(v string) *BalanceLotUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableSourceType(v *string) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *BalanceLotUpdateOne) SetSourceRef(v string) *BalanceLotUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableSourceRef(v *string) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *BalanceLotUpdateOne) ClearSourceRef() *BalanceLotUpdateOne {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetOriginalAmount sets the "original_amount" field.
func (_u *BalanceLotUpdateOne) SetOriginalAmount(v float64) *BalanceLotUpdateOne {
	_u.mutation.ResetOriginalAmount()
	_u.mutation.SetOriginalAmount(v)
	return _u
}

// SetNillableOriginalAmount sets the "original_amount" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableOriginalAmount(v *float64) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetOriginalAmount(*v)
	}
	return _u
}

// AddOriginalAmount adds value to the "original_amount" field.
func (_u *BalanceLotUpdateOne) AddOriginalAmount(v float64) *BalanceLotUpdateOne {
	_u.mutation.AddOriginalAmount(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *BalanceLotUpdateOne) SetRemainingAmount(v float64) *BalanceLotUpdateOne {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableRemainingAmount(v *float64) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *BalanceLotUpdateOne) AddRemainingAmount(v float64) *BalanceLotUpdateOne {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *BalanceLotUpdateOne) SetStatus(v string) *BalanceLotUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableStatus(v *string) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *BalanceLotUpdateOne) SetExpiresAt(v time.Time) *BalanceLotUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableExpiresAt(v *time.Time) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *BalanceLotUpdateOne) SetExpiredAt(v time.Time) *BalanceLotUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableExpiredAt(v *time.Time) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *BalanceLotUpdateOne) ClearExpiredAt() *BalanceLotUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLotUpdateOne) SetDescription(v string) *BalanceLotUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLotUpdateOne) SetNillableDescription(v *string) *BalanceLotUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BalanceLotUpdateOne) SetUser(v *User) *BalanceLotUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the BalanceLotMutation object of the builder.
func (_u *BalanceLotUpdateOne) Mutation() *BalanceLotMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BalanceLotUpdateOne) ClearUser() *BalanceLotUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the BalanceLotUpdate builder.
func (_u *BalanceLotUpdateOne) Where(ps ...predicate.BalanceLot) *BalanceLotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceLotUpdateOne) Select(field string, fields ...string) *BalanceLotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceLot entity.
func (_u *BalanceLotUpdateOne) Save(ctx context.Context) (*BalanceLot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLotUpdateOne) SaveX(ctx context.Context) *BalanceLot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceLotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balancelot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLotUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := balancelot.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := balancelot.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceRef(); ok {
		if err := balancelot.SourceRefValidator(v); err != nil {
			return &ValidationError{Name: "source_ref", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.source_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := balancelot.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BalanceLot.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceLot.user"`)
	}
	return nil
}

func (_u *BalanceLotUpdateOne) sqlSave(ctx context.Context) (_node *BalanceLot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelot.Table, balancelot.Columns, sqlgraph.NewFieldSpec(balancelot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceLot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancelot.FieldID)
		for _, f := range fields {
			if !balancelot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancelot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balancelot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(balancelot.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(balancelot.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(balancelot.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalAmount(); ok {
		_spec.SetField(balancelot.FieldOriginalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalAmount(); ok {
		_spec.AddField(balancelot.FieldOriginalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(balancelot.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(balancelot.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(balancelot.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(balancelot.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(balancelot.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(balancelot.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balancelot.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelot.UserTable,
			Columns: []string{balancelot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelot.UserTable,
			Columns: []string{balancelot.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceLot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
