// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/copilotplatformconfig"
)

// CopilotPlatformConfig is the model entity for the CopilotPlatformConfig schema.
type CopilotPlatformConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Copilot plan type: individual_free / individual_pro / individual_pro_plus / business / enterprise
	PlanType string `json:"plan_type,omitempty"`
	// Max output tokens for this plan type; NULL = use system default
	MaxOutputTokens *int64 `json:"max_output_tokens,omitempty"`
	// Max request body size in KB for this plan type; NULL = use system default
	MaxBodyKB *int `json:"max_body_kb,omitempty"`
	// Model name rewriting map {from: to}; NULL = no mapping default
	ModelMapping map[string]string `json:"model_mapping,omitempty"`
	// Allowed model list; NULL = allow all (no whitelist default)
	ModelWhitelist []string `json:"model_whitelist,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CopilotPlatformConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case copilotplatformconfig.FieldModelMapping, copilotplatformconfig.FieldModelWhitelist:
			values[i] = new([]byte)
		case copilotplatformconfig.FieldID, copilotplatformconfig.FieldMaxOutputTokens, copilotplatformconfig.FieldMaxBodyKB:
			values[i] = new(sql.NullInt64)
		case copilotplatformconfig.FieldPlanType:
			values[i] = new(sql.NullString)
		case copilotplatformconfig.FieldCreatedAt, copilotplatformconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CopilotPlatformConfig fields.
func (_m *CopilotPlatformConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case copilotplatformconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case copilotplatformconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case copilotplatformconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case copilotplatformconfig.FieldPlanType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_type", values[i])
			} else if value.Valid {
				_m.PlanType = value.String
			}
		case copilotplatformconfig.FieldMaxOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_output_tokens", values[i])
			} else if value.Valid {
				_m.MaxOutputTokens = new(int64)
				*_m.MaxOutputTokens = value.Int64
			}
		case copilotplatformconfig.FieldMaxBodyKB:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_body_kb", values[i])
			} else if value.Valid {
				_m.MaxBodyKB = new(int)
				*_m.MaxBodyKB = int(value.Int64)
			}
		case copilotplatformconfig.FieldModelMapping:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_mapping", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelMapping); err != nil {
					return fmt.Errorf("unmarshal field model_mapping: %w", err)
				}
			}
		case copilotplatformconfig.FieldModelWhitelist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_whitelist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelWhitelist); err != nil {
					return fmt.Errorf("unmarshal field model_whitelist: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CopilotPlatformConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CopilotPlatformConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CopilotPlatformConfig.
// Note that you need to call CopilotPlatformConfig.Unwrap() before calling this method if this CopilotPlatformConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CopilotPlatformConfig) Update() *CopilotPlatformConfigUpdateOne {
	return NewCopilotPlatformConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CopilotPlatformConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CopilotPlatformConfig) Unwrap() *CopilotPlatformConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CopilotPlatformConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CopilotPlatformConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CopilotPlatformConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("plan_type=")
	builder.WriteString(_m.PlanType)
	builder.WriteString(", ")
	if v := _m.MaxOutputTokens; v != nil {
		builder.WriteString("max_output_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MaxBodyKB; v != nil {
		builder.WriteString("max_body_kb=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model_mapping=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelMapping))
	builder.WriteString(", ")
	builder.WriteString("model_whitelist=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelWhitelist))
	builder.WriteByte(')')
	return builder.String()
}

// CopilotPlatformConfigs is a parsable slice of CopilotPlatformConfig.
type CopilotPlatformConfigs []*CopilotPlatformConfig
