// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/copilotplatformconfig"
)

// CopilotPlatformConfigCreate is the builder for creating a CopilotPlatformConfig entity.
type CopilotPlatformConfigCreate struct {
	config
	mutation *CopilotPlatformConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CopilotPlatformConfigCreate) SetCreatedAt(v time.Time) *CopilotPlatformConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CopilotPlatformConfigCreate) SetNillableCreatedAt(v *time.Time) *CopilotPlatformConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CopilotPlatformConfigCreate) SetUpdatedAt(v time.Time) *CopilotPlatformConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CopilotPlatformConfigCreate) SetNillableUpdatedAt(v *time.Time) *CopilotPlatformConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPlanType sets the "plan_type" field.
func (_c *CopilotPlatformConfigCreate) SetPlanType(v string) *CopilotPlatformConfigCreate {
	_c.mutation.SetPlanType(v)
	return _c
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_c *CopilotPlatformConfigCreate) SetMaxOutputTokens(v int64) *CopilotPlatformConfigCreate {
	_c.mutation.SetMaxOutputTokens(v)
	return _c
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_c *CopilotPlatformConfigCreate) SetNillableMaxOutputTokens(v *int64) *CopilotPlatformConfigCreate {
	if v != nil {
		_c.SetMaxOutputTokens(*v)
	}
	return _c
}

// SetMaxBodyKB sets the "max_body_kb" field.
func (_c *CopilotPlatformConfigCreate) SetMaxBodyKB(v int) *CopilotPlatformConfigCreate {
	_c.mutation.SetMaxBodyKB(v)
	return _c
}

// SetNillableMaxBodyKB sets the "max_body_kb" field if the given value is not nil.
func (_c *CopilotPlatformConfigCreate) SetNillableMaxBodyKB(v *int) *CopilotPlatformConfigCreate {
	if v != nil {
		_c.SetMaxBodyKB(*v)
	}
	return _c
}

// SetModelMapping sets the "model_mapping" field.
func (_c *CopilotPlatformConfigCreate) SetModelMapping(v map[string]string) *CopilotPlatformConfigCreate {
	_c.mutation.SetModelMapping(v)
	return _c
}

// SetModelWhitelist sets the "model_whitelist" field.
func (_c *CopilotPlatformConfigCreate) SetModelWhitelist(v []string) *CopilotPlatformConfigCreate {
	_c.mutation.SetModelWhitelist(v)
	return _c
}

// Mutation returns the CopilotPlatformConfigMutation object of the builder.
func (_c *CopilotPlatformConfigCreate) Mutation() *CopilotPlatformConfigMutation {
	return _c.mutation
}

// Save creates the CopilotPlatformConfig in the database.
func (_c *CopilotPlatformConfigCreate) Save(ctx context.Context) (*CopilotPlatformConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CopilotPlatformConfigCreate) SaveX(ctx context.Context) *CopilotPlatformConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotPlatformConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotPlatformConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CopilotPlatformConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := copilotplatformconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := copilotplatformconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CopilotPlatformConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CopilotPlatformConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CopilotPlatformConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.PlanType(); !ok {
		return &ValidationError{Name: "plan_type", err: errors.New(`ent: missing required field "CopilotPlatformConfig.plan_type"`)}
	}
	if v, ok := _c.mutation.PlanType(); ok {
		if err := copilotplatformconfig.PlanTypeValidator(v); err != nil {
			return &ValidationError{Name: "plan_type", err: fmt.Errorf(`ent: validator failed for field "CopilotPlatformConfig.plan_type": %w`, err)}
		}
	}
	return nil
}

func (_c *CopilotPlatformConfigCreate) sqlSave(ctx context.Context) (*CopilotPlatformConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CopilotPlatformConfigCreate) createSpec() (*CopilotPlatformConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CopilotPlatformConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(copilotplatformconfig.Table, sqlgraph.NewFieldSpec(copilotplatformconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(copilotplatformconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(copilotplatformconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PlanType(); ok {
		_spec.SetField(copilotplatformconfig.FieldPlanType, field.TypeString, value)
		_node.PlanType = value
	}
	if value, ok := _c.mutation.MaxOutputTokens(); ok {
		_spec.SetField(copilotplatformconfig.FieldMaxOutputTokens, field.TypeInt64, value)
		_node.MaxOutputTokens = &value
	}
	if value, ok := _c.mutation.MaxBodyKB(); ok {
		_spec.SetField(copilotplatformconfig.FieldMaxBodyKB, field.TypeInt, value)
		_node.MaxBodyKB = &value
	}
	if value, ok := _c.mutation.ModelMapping(); ok {
		_spec.SetField(copilotplatformconfig.FieldModelMapping, field.TypeJSON, value)
		_node.ModelMapping = value
	}
	if value, ok := _c.mutation.ModelWhitelist(); ok {
		_spec.SetField(copilotplatformconfig.FieldModelWhitelist, field.TypeJSON, value)
		_node.ModelWhitelist = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotPlatformConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotPlatformConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotPlatformConfigCreate) OnConflict(opts ...sql.ConflictOption) *CopilotPlatformConfigUpsertOne {
	_c.conflict = opts
	return &CopilotPlatformConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotPlatformConfigCreate) OnConflictColumns(columns ...string) *CopilotPlatformConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotPlatformConfigUpsertOne{
		create: _c,
	}
}

type (
	// CopilotPlatformConfigUpsertOne is the builder for "upsert"-ing
	//  one CopilotPlatformConfig node.
	CopilotPlatformConfigUpsertOne struct {
		create *CopilotPlatformConfigCreate
	}

	// CopilotPlatformConfigUpsert is the "OnConflict" setter.
	CopilotPlatformConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotPlatformConfigUpsert) SetUpdatedAt(v time.Time) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdateUpdatedAt() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldUpdatedAt)
	return u
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotPlatformConfigUpsert) SetPlanType(v string) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldPlanType, v)
	return u
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdatePlanType() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldPlanType)
	return u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsert) SetMaxOutputTokens(v int64) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldMaxOutputTokens, v)
	return u
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdateMaxOutputTokens() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldMaxOutputTokens)
	return u
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsert) AddMaxOutputTokens(v int64) *CopilotPlatformConfigUpsert {
	u.Add(copilotplatformconfig.FieldMaxOutputTokens, v)
	return u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsert) ClearMaxOutputTokens() *CopilotPlatformConfigUpsert {
	u.SetNull(copilotplatformconfig.FieldMaxOutputTokens)
	return u
}

// SetMaxBodyKB sets the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsert) SetMaxBodyKB(v int) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldMaxBodyKB, v)
	return u
}

// UpdateMaxBodyKB sets the "max_body_kb" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdateMaxBodyKB() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldMaxBodyKB)
	return u
}

// AddMaxBodyKB adds v to the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsert) AddMaxBodyKB(v int) *CopilotPlatformConfigUpsert {
	u.Add(copilotplatformconfig.FieldMaxBodyKB, v)
	return u
}

// ClearMaxBodyKB clears the value of the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsert) ClearMaxBodyKB() *CopilotPlatformConfigUpsert {
	u.SetNull(copilotplatformconfig.FieldMaxBodyKB)
	return u
}

// SetModelMapping sets the "model_mapping" field.
func (u *CopilotPlatformConfigUpsert) SetModelMapping(v map[string]string) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldModelMapping, v)
	return u
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdateModelMapping() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldModelMapping)
	return u
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *CopilotPlatformConfigUpsert) ClearModelMapping() *CopilotPlatformConfigUpsert {
	u.SetNull(copilotplatformconfig.FieldModelMapping)
	return u
}

// SetModelWhitelist sets the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsert) SetModelWhitelist(v []string) *CopilotPlatformConfigUpsert {
	u.Set(copilotplatformconfig.FieldModelWhitelist, v)
	return u
}

// UpdateModelWhitelist sets the "model_whitelist" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsert) UpdateModelWhitelist() *CopilotPlatformConfigUpsert {
	u.SetExcluded(copilotplatformconfig.FieldModelWhitelist)
	return u
}

// ClearModelWhitelist clears the value of the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsert) ClearModelWhitelist() *CopilotPlatformConfigUpsert {
	u.SetNull(copilotplatformconfig.FieldModelWhitelist)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotPlatformConfigUpsertOne) UpdateNewValues() *CopilotPlatformConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(copilotplatformconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CopilotPlatformConfigUpsertOne) Ignore() *CopilotPlatformConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotPlatformConfigUpsertOne) DoNothing() *CopilotPlatformConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotPlatformConfigCreate.OnConflict
// documentation for more info.
func (u *CopilotPlatformConfigUpsertOne) Update(set func(*CopilotPlatformConfigUpsert)) *CopilotPlatformConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotPlatformConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotPlatformConfigUpsertOne) SetUpdatedAt(v time.Time) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdateUpdatedAt() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotPlatformConfigUpsertOne) SetPlanType(v string) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdatePlanType() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdatePlanType()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertOne) SetMaxOutputTokens(v int64) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertOne) AddMaxOutputTokens(v int64) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdateMaxOutputTokens() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertOne) ClearMaxOutputTokens() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearMaxOutputTokens()
	})
}

// SetMaxBodyKB sets the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertOne) SetMaxBodyKB(v int) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetMaxBodyKB(v)
	})
}

// AddMaxBodyKB adds v to the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertOne) AddMaxBodyKB(v int) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.AddMaxBodyKB(v)
	})
}

// UpdateMaxBodyKB sets the "max_body_kb" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdateMaxBodyKB() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateMaxBodyKB()
	})
}

// ClearMaxBodyKB clears the value of the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertOne) ClearMaxBodyKB() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearMaxBodyKB()
	})
}

// SetModelMapping sets the "model_mapping" field.
func (u *CopilotPlatformConfigUpsertOne) SetModelMapping(v map[string]string) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetModelMapping(v)
	})
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdateModelMapping() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateModelMapping()
	})
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *CopilotPlatformConfigUpsertOne) ClearModelMapping() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearModelMapping()
	})
}

// SetModelWhitelist sets the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsertOne) SetModelWhitelist(v []string) *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetModelWhitelist(v)
	})
}

// UpdateModelWhitelist sets the "model_whitelist" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertOne) UpdateModelWhitelist() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateModelWhitelist()
	})
}

// ClearModelWhitelist clears the value of the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsertOne) ClearModelWhitelist() *CopilotPlatformConfigUpsertOne {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearModelWhitelist()
	})
}

// Exec executes the query.
func (u *CopilotPlatformConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotPlatformConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotPlatformConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CopilotPlatformConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CopilotPlatformConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CopilotPlatformConfigCreateBulk is the builder for creating many CopilotPlatformConfig entities in bulk.
type CopilotPlatformConfigCreateBulk struct {
	config
	err      error
	builders []*CopilotPlatformConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the CopilotPlatformConfig entities in the database.
func (_c *CopilotPlatformConfigCreateBulk) Save(ctx context.Context) ([]*CopilotPlatformConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CopilotPlatformConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CopilotPlatformConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CopilotPlatformConfigCreateBulk) SaveX(ctx context.Context) []*CopilotPlatformConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopilotPlatformConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopilotPlatformConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopilotPlatformConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopilotPlatformConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopilotPlatformConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *CopilotPlatformConfigUpsertBulk {
	_c.conflict = opts
	return &CopilotPlatformConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopilotPlatformConfigCreateBulk) OnConflictColumns(columns ...string) *CopilotPlatformConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopilotPlatformConfigUpsertBulk{
		create: _c,
	}
}

// CopilotPlatformConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of CopilotPlatformConfig nodes.
type CopilotPlatformConfigUpsertBulk struct {
	create *CopilotPlatformConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CopilotPlatformConfigUpsertBulk) UpdateNewValues() *CopilotPlatformConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(copilotplatformconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopilotPlatformConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CopilotPlatformConfigUpsertBulk) Ignore() *CopilotPlatformConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopilotPlatformConfigUpsertBulk) DoNothing() *CopilotPlatformConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopilotPlatformConfigCreateBulk.OnConflict
// documentation for more info.
func (u *CopilotPlatformConfigUpsertBulk) Update(set func(*CopilotPlatformConfigUpsert)) *CopilotPlatformConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopilotPlatformConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopilotPlatformConfigUpsertBulk) SetUpdatedAt(v time.Time) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdateUpdatedAt() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CopilotPlatformConfigUpsertBulk) SetPlanType(v string) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdatePlanType() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdatePlanType()
	})
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertBulk) SetMaxOutputTokens(v int64) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetMaxOutputTokens(v)
	})
}

// AddMaxOutputTokens adds v to the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertBulk) AddMaxOutputTokens(v int64) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.AddMaxOutputTokens(v)
	})
}

// UpdateMaxOutputTokens sets the "max_output_tokens" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdateMaxOutputTokens() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateMaxOutputTokens()
	})
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (u *CopilotPlatformConfigUpsertBulk) ClearMaxOutputTokens() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearMaxOutputTokens()
	})
}

// SetMaxBodyKB sets the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertBulk) SetMaxBodyKB(v int) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetMaxBodyKB(v)
	})
}

// AddMaxBodyKB adds v to the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertBulk) AddMaxBodyKB(v int) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.AddMaxBodyKB(v)
	})
}

// UpdateMaxBodyKB sets the "max_body_kb" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdateMaxBodyKB() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateMaxBodyKB()
	})
}

// ClearMaxBodyKB clears the value of the "max_body_kb" field.
func (u *CopilotPlatformConfigUpsertBulk) ClearMaxBodyKB() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearMaxBodyKB()
	})
}

// SetModelMapping sets the "model_mapping" field.
func (u *CopilotPlatformConfigUpsertBulk) SetModelMapping(v map[string]string) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetModelMapping(v)
	})
}

// UpdateModelMapping sets the "model_mapping" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdateModelMapping() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateModelMapping()
	})
}

// ClearModelMapping clears the value of the "model_mapping" field.
func (u *CopilotPlatformConfigUpsertBulk) ClearModelMapping() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearModelMapping()
	})
}

// SetModelWhitelist sets the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsertBulk) SetModelWhitelist(v []string) *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.SetModelWhitelist(v)
	})
}

// UpdateModelWhitelist sets the "model_whitelist" field to the value that was provided on create.
func (u *CopilotPlatformConfigUpsertBulk) UpdateModelWhitelist() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.UpdateModelWhitelist()
	})
}

// ClearModelWhitelist clears the value of the "model_whitelist" field.
func (u *CopilotPlatformConfigUpsertBulk) ClearModelWhitelist() *CopilotPlatformConfigUpsertBulk {
	return u.Update(func(s *CopilotPlatformConfigUpsert) {
		s.ClearModelWhitelist()
	})
}

// Exec executes the query.
func (u *CopilotPlatformConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CopilotPlatformConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopilotPlatformConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopilotPlatformConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
