// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotterycoupon"
)

// LotteryCouponCreate is the builder for creating a LotteryCoupon entity.
type LotteryCouponCreate struct {
	config
	mutation *LotteryCouponMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *LotteryCouponCreate) SetActivityID(v int64) *LotteryCouponCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LotteryCouponCreate) SetUserID(v int64) *LotteryCouponCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCouponType sets the "coupon_type" field.
func (_c *LotteryCouponCreate) SetCouponType(v string) *LotteryCouponCreate {
	_c.mutation.SetCouponType(v)
	return _c
}

// SetDiscountPercent sets the "discount_percent" field.
func (_c *LotteryCouponCreate) SetDiscountPercent(v int) *LotteryCouponCreate {
	_c.mutation.SetDiscountPercent(v)
	return _c
}

// SetNillableDiscountPercent sets the "discount_percent" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableDiscountPercent(v *int) *LotteryCouponCreate {
	if v != nil {
		_c.SetDiscountPercent(*v)
	}
	return _c
}

// SetReductionAmount sets the "reduction_amount" field.
func (_c *LotteryCouponCreate) SetReductionAmount(v float64) *LotteryCouponCreate {
	_c.mutation.SetReductionAmount(v)
	return _c
}

// SetNillableReductionAmount sets the "reduction_amount" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableReductionAmount(v *float64) *LotteryCouponCreate {
	if v != nil {
		_c.SetReductionAmount(*v)
	}
	return _c
}

// SetApplicableScope sets the "applicable_scope" field.
func (_c *LotteryCouponCreate) SetApplicableScope(v string) *LotteryCouponCreate {
	_c.mutation.SetApplicableScope(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryCouponCreate) SetStatus(v string) *LotteryCouponCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableStatus(v *string) *LotteryCouponCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUsedAt sets the "used_at" field.
func (_c *LotteryCouponCreate) SetUsedAt(v time.Time) *LotteryCouponCreate {
	_c.mutation.SetUsedAt(v)
	return _c
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableUsedAt(v *time.Time) *LotteryCouponCreate {
	if v != nil {
		_c.SetUsedAt(*v)
	}
	return _c
}

// SetUsedOrderID sets the "used_order_id" field.
func (_c *LotteryCouponCreate) SetUsedOrderID(v string) *LotteryCouponCreate {
	_c.mutation.SetUsedOrderID(v)
	return _c
}

// SetNillableUsedOrderID sets the "used_order_id" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableUsedOrderID(v *string) *LotteryCouponCreate {
	if v != nil {
		_c.SetUsedOrderID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *LotteryCouponCreate) SetExpiresAt(v time.Time) *LotteryCouponCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetReminded sets the "reminded" field.
func (_c *LotteryCouponCreate) SetReminded(v bool) *LotteryCouponCreate {
	_c.mutation.SetReminded(v)
	return _c
}

// SetNillableReminded sets the "reminded" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableReminded(v *bool) *LotteryCouponCreate {
	if v != nil {
		_c.SetReminded(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryCouponCreate) SetCreatedAt(v time.Time) *LotteryCouponCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryCouponCreate) SetNillableCreatedAt(v *time.Time) *LotteryCouponCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_c *LotteryCouponCreate) SetActivity(v *LotteryActivity) *LotteryCouponCreate {
	return _c.SetActivityID(v.ID)
}

// Mutation returns the LotteryCouponMutation object of the builder.
func (_c *LotteryCouponCreate) Mutation() *LotteryCouponMutation {
	return _c.mutation
}

// Save creates the LotteryCoupon in the database.
func (_c *LotteryCouponCreate) Save(ctx context.Context) (*LotteryCoupon, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryCouponCreate) SaveX(ctx context.Context) *LotteryCoupon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCouponCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCouponCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryCouponCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotterycoupon.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Reminded(); !ok {
		v := lotterycoupon.DefaultReminded
		_c.mutation.SetReminded(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterycoupon.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryCouponCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "LotteryCoupon.activity_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryCoupon.user_id"`)}
	}
	if _, ok := _c.mutation.CouponType(); !ok {
		return &ValidationError{Name: "coupon_type", err: errors.New(`ent: missing required field "LotteryCoupon.coupon_type"`)}
	}
	if v, ok := _c.mutation.CouponType(); ok {
		if err := lotterycoupon.CouponTypeValidator(v); err != nil {
			return &ValidationError{Name: "coupon_type", err: fmt.Errorf(`ent: validator failed for field "LotteryCoupon.coupon_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ApplicableScope(); !ok {
		return &ValidationError{Name: "applicable_scope", err: errors.New(`ent: missing required field "LotteryCoupon.applicable_scope"`)}
	}
	if v, ok := _c.mutation.ApplicableScope(); ok {
		if err := lotterycoupon.ApplicableScopeValidator(v); err != nil {
			return &ValidationError{Name: "applicable_scope", err: fmt.Errorf(`ent: validator failed for field "LotteryCoupon.applicable_scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryCoupon.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotterycoupon.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryCoupon.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UsedOrderID(); ok {
		if err := lotterycoupon.UsedOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "used_order_id", err: fmt.Errorf(`ent: validator failed for field "LotteryCoupon.used_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "LotteryCoupon.expires_at"`)}
	}
	if _, ok := _c.mutation.Reminded(); !ok {
		return &ValidationError{Name: "reminded", err: errors.New(`ent: missing required field "LotteryCoupon.reminded"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryCoupon.created_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "LotteryCoupon.activity"`)}
	}
	return nil
}

func (_c *LotteryCouponCreate) sqlSave(ctx context.Context) (*LotteryCoupon, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryCouponCreate) createSpec() (*LotteryCoupon, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryCoupon{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterycoupon.Table, sqlgraph.NewFieldSpec(lotterycoupon.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotterycoupon.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CouponType(); ok {
		_spec.SetField(lotterycoupon.FieldCouponType, field.TypeString, value)
		_node.CouponType = value
	}
	if value, ok := _c.mutation.DiscountPercent(); ok {
		_spec.SetField(lotterycoupon.FieldDiscountPercent, field.TypeInt, value)
		_node.DiscountPercent = &value
	}
	if value, ok := _c.mutation.ReductionAmount(); ok {
		_spec.SetField(lotterycoupon.FieldReductionAmount, field.TypeFloat64, value)
		_node.ReductionAmount = &value
	}
	if value, ok := _c.mutation.ApplicableScope(); ok {
		_spec.SetField(lotterycoupon.FieldApplicableScope, field.TypeString, value)
		_node.ApplicableScope = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotterycoupon.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UsedAt(); ok {
		_spec.SetField(lotterycoupon.FieldUsedAt, field.TypeTime, value)
		_node.UsedAt = &value
	}
	if value, ok := _c.mutation.UsedOrderID(); ok {
		_spec.SetField(lotterycoupon.FieldUsedOrderID, field.TypeString, value)
		_node.UsedOrderID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(lotterycoupon.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Reminded(); ok {
		_spec.SetField(lotterycoupon.FieldReminded, field.TypeBool, value)
		_node.Reminded = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterycoupon.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotterycoupon.ActivityTable,
			Columns: []string{lotterycoupon.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCoupon.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCouponUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCouponCreate) OnConflict(opts ...sql.ConflictOption) *LotteryCouponUpsertOne {
	_c.conflict = opts
	return &LotteryCouponUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCouponCreate) OnConflictColumns(columns ...string) *LotteryCouponUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCouponUpsertOne{
		create: _c,
	}
}

type (
	// LotteryCouponUpsertOne is the builder for "upsert"-ing
	//  one LotteryCoupon node.
	LotteryCouponUpsertOne struct {
		create *LotteryCouponCreate
	}

	// LotteryCouponUpsert is the "OnConflict" setter.
	LotteryCouponUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *LotteryCouponUpsert) SetActivityID(v int64) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateActivityID() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldActivityID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryCouponUpsert) SetUserID(v int64) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateUserID() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryCouponUpsert) AddUserID(v int64) *LotteryCouponUpsert {
	u.Add(lotterycoupon.FieldUserID, v)
	return u
}

// SetCouponType sets the "coupon_type" field.
func (u *LotteryCouponUpsert) SetCouponType(v string) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldCouponType, v)
	return u
}

// UpdateCouponType sets the "coupon_type" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateCouponType() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldCouponType)
	return u
}

// SetDiscountPercent sets the "discount_percent" field.
func (u *LotteryCouponUpsert) SetDiscountPercent(v int) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldDiscountPercent, v)
	return u
}

// UpdateDiscountPercent sets the "discount_percent" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateDiscountPercent() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldDiscountPercent)
	return u
}

// AddDiscountPercent adds v to the "discount_percent" field.
func (u *LotteryCouponUpsert) AddDiscountPercent(v int) *LotteryCouponUpsert {
	u.Add(lotterycoupon.FieldDiscountPercent, v)
	return u
}

// ClearDiscountPercent clears the value of the "discount_percent" field.
func (u *LotteryCouponUpsert) ClearDiscountPercent() *LotteryCouponUpsert {
	u.SetNull(lotterycoupon.FieldDiscountPercent)
	return u
}

// SetReductionAmount sets the "reduction_amount" field.
func (u *LotteryCouponUpsert) SetReductionAmount(v float64) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldReductionAmount, v)
	return u
}

// UpdateReductionAmount sets the "reduction_amount" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateReductionAmount() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldReductionAmount)
	return u
}

// AddReductionAmount adds v to the "reduction_amount" field.
func (u *LotteryCouponUpsert) AddReductionAmount(v float64) *LotteryCouponUpsert {
	u.Add(lotterycoupon.FieldReductionAmount, v)
	return u
}

// ClearReductionAmount clears the value of the "reduction_amount" field.
func (u *LotteryCouponUpsert) ClearReductionAmount() *LotteryCouponUpsert {
	u.SetNull(lotterycoupon.FieldReductionAmount)
	return u
}

// SetApplicableScope sets the "applicable_scope" field.
func (u *LotteryCouponUpsert) SetApplicableScope(v string) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldApplicableScope, v)
	return u
}

// UpdateApplicableScope sets the "applicable_scope" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateApplicableScope() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldApplicableScope)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryCouponUpsert) SetStatus(v string) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateStatus() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldStatus)
	return u
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryCouponUpsert) SetUsedAt(v time.Time) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldUsedAt, v)
	return u
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateUsedAt() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldUsedAt)
	return u
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryCouponUpsert) ClearUsedAt() *LotteryCouponUpsert {
	u.SetNull(lotterycoupon.FieldUsedAt)
	return u
}

// SetUsedOrderID sets the "used_order_id" field.
func (u *LotteryCouponUpsert) SetUsedOrderID(v string) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldUsedOrderID, v)
	return u
}

// UpdateUsedOrderID sets the "used_order_id" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateUsedOrderID() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldUsedOrderID)
	return u
}

// ClearUsedOrderID clears the value of the "used_order_id" field.
func (u *LotteryCouponUpsert) ClearUsedOrderID() *LotteryCouponUpsert {
	u.SetNull(lotterycoupon.FieldUsedOrderID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryCouponUpsert) SetExpiresAt(v time.Time) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateExpiresAt() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldExpiresAt)
	return u
}

// SetReminded sets the "reminded" field.
func (u *LotteryCouponUpsert) SetReminded(v bool) *LotteryCouponUpsert {
	u.Set(lotterycoupon.FieldReminded, v)
	return u
}

// UpdateReminded sets the "reminded" field to the value that was provided on create.
func (u *LotteryCouponUpsert) UpdateReminded() *LotteryCouponUpsert {
	u.SetExcluded(lotterycoupon.FieldReminded)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCouponUpsertOne) UpdateNewValues() *LotteryCouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterycoupon.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryCouponUpsertOne) Ignore() *LotteryCouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCouponUpsertOne) DoNothing() *LotteryCouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCouponCreate.OnConflict
// documentation for more info.
func (u *LotteryCouponUpsertOne) Update(set func(*LotteryCouponUpsert)) *LotteryCouponUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCouponUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryCouponUpsertOne) SetActivityID(v int64) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateActivityID() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryCouponUpsertOne) SetUserID(v int64) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryCouponUpsertOne) AddUserID(v int64) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateUserID() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUserID()
	})
}

// SetCouponType sets the "coupon_type" field.
func (u *LotteryCouponUpsertOne) SetCouponType(v string) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetCouponType(v)
	})
}

// UpdateCouponType sets the "coupon_type" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateCouponType() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateCouponType()
	})
}

// SetDiscountPercent sets the "discount_percent" field.
func (u *LotteryCouponUpsertOne) SetDiscountPercent(v int) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetDiscountPercent(v)
	})
}

// AddDiscountPercent adds v to the "discount_percent" field.
func (u *LotteryCouponUpsertOne) AddDiscountPercent(v int) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddDiscountPercent(v)
	})
}

// UpdateDiscountPercent sets the "discount_percent" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateDiscountPercent() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateDiscountPercent()
	})
}

// ClearDiscountPercent clears the value of the "discount_percent" field.
func (u *LotteryCouponUpsertOne) ClearDiscountPercent() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearDiscountPercent()
	})
}

// SetReductionAmount sets the "reduction_amount" field.
func (u *LotteryCouponUpsertOne) SetReductionAmount(v float64) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetReductionAmount(v)
	})
}

// AddReductionAmount adds v to the "reduction_amount" field.
func (u *LotteryCouponUpsertOne) AddReductionAmount(v float64) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddReductionAmount(v)
	})
}

// UpdateReductionAmount sets the "reduction_amount" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateReductionAmount() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateReductionAmount()
	})
}

// ClearReductionAmount clears the value of the "reduction_amount" field.
func (u *LotteryCouponUpsertOne) ClearReductionAmount() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearReductionAmount()
	})
}

// SetApplicableScope sets the "applicable_scope" field.
func (u *LotteryCouponUpsertOne) SetApplicableScope(v string) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetApplicableScope(v)
	})
}

// UpdateApplicableScope sets the "applicable_scope" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateApplicableScope() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateApplicableScope()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCouponUpsertOne) SetStatus(v string) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateStatus() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateStatus()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryCouponUpsertOne) SetUsedAt(v time.Time) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateUsedAt() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryCouponUpsertOne) ClearUsedAt() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearUsedAt()
	})
}

// SetUsedOrderID sets the "used_order_id" field.
func (u *LotteryCouponUpsertOne) SetUsedOrderID(v string) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUsedOrderID(v)
	})
}

// UpdateUsedOrderID sets the "used_order_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateUsedOrderID() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUsedOrderID()
	})
}

// ClearUsedOrderID clears the value of the "used_order_id" field.
func (u *LotteryCouponUpsertOne) ClearUsedOrderID() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearUsedOrderID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryCouponUpsertOne) SetExpiresAt(v time.Time) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateExpiresAt() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetReminded sets the "reminded" field.
func (u *LotteryCouponUpsertOne) SetReminded(v bool) *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetReminded(v)
	})
}

// UpdateReminded sets the "reminded" field to the value that was provided on create.
func (u *LotteryCouponUpsertOne) UpdateReminded() *LotteryCouponUpsertOne {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateReminded()
	})
}

// Exec executes the query.
func (u *LotteryCouponUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCouponCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCouponUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryCouponUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryCouponUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryCouponCreateBulk is the builder for creating many LotteryCoupon entities in bulk.
type LotteryCouponCreateBulk struct {
	config
	err      error
	builders []*LotteryCouponCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryCoupon entities in the database.
func (_c *LotteryCouponCreateBulk) Save(ctx context.Context) ([]*LotteryCoupon, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryCoupon, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryCouponMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryCouponCreateBulk) SaveX(ctx context.Context) []*LotteryCoupon {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCouponCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCouponCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCoupon.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCouponUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCouponCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryCouponUpsertBulk {
	_c.conflict = opts
	return &LotteryCouponUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCouponCreateBulk) OnConflictColumns(columns ...string) *LotteryCouponUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCouponUpsertBulk{
		create: _c,
	}
}

// LotteryCouponUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryCoupon nodes.
type LotteryCouponUpsertBulk struct {
	create *LotteryCouponCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCouponUpsertBulk) UpdateNewValues() *LotteryCouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterycoupon.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCoupon.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryCouponUpsertBulk) Ignore() *LotteryCouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCouponUpsertBulk) DoNothing() *LotteryCouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCouponCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryCouponUpsertBulk) Update(set func(*LotteryCouponUpsert)) *LotteryCouponUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCouponUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryCouponUpsertBulk) SetActivityID(v int64) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateActivityID() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryCouponUpsertBulk) SetUserID(v int64) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryCouponUpsertBulk) AddUserID(v int64) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateUserID() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUserID()
	})
}

// SetCouponType sets the "coupon_type" field.
func (u *LotteryCouponUpsertBulk) SetCouponType(v string) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetCouponType(v)
	})
}

// UpdateCouponType sets the "coupon_type" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateCouponType() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateCouponType()
	})
}

// SetDiscountPercent sets the "discount_percent" field.
func (u *LotteryCouponUpsertBulk) SetDiscountPercent(v int) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetDiscountPercent(v)
	})
}

// AddDiscountPercent adds v to the "discount_percent" field.
func (u *LotteryCouponUpsertBulk) AddDiscountPercent(v int) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddDiscountPercent(v)
	})
}

// UpdateDiscountPercent sets the "discount_percent" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateDiscountPercent() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateDiscountPercent()
	})
}

// ClearDiscountPercent clears the value of the "discount_percent" field.
func (u *LotteryCouponUpsertBulk) ClearDiscountPercent() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearDiscountPercent()
	})
}

// SetReductionAmount sets the "reduction_amount" field.
func (u *LotteryCouponUpsertBulk) SetReductionAmount(v float64) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetReductionAmount(v)
	})
}

// AddReductionAmount adds v to the "reduction_amount" field.
func (u *LotteryCouponUpsertBulk) AddReductionAmount(v float64) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.AddReductionAmount(v)
	})
}

// UpdateReductionAmount sets the "reduction_amount" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateReductionAmount() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateReductionAmount()
	})
}

// ClearReductionAmount clears the value of the "reduction_amount" field.
func (u *LotteryCouponUpsertBulk) ClearReductionAmount() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearReductionAmount()
	})
}

// SetApplicableScope sets the "applicable_scope" field.
func (u *LotteryCouponUpsertBulk) SetApplicableScope(v string) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetApplicableScope(v)
	})
}

// UpdateApplicableScope sets the "applicable_scope" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateApplicableScope() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateApplicableScope()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCouponUpsertBulk) SetStatus(v string) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateStatus() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateStatus()
	})
}

// SetUsedAt sets the "used_at" field.
func (u *LotteryCouponUpsertBulk) SetUsedAt(v time.Time) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUsedAt(v)
	})
}

// UpdateUsedAt sets the "used_at" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateUsedAt() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUsedAt()
	})
}

// ClearUsedAt clears the value of the "used_at" field.
func (u *LotteryCouponUpsertBulk) ClearUsedAt() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearUsedAt()
	})
}

// SetUsedOrderID sets the "used_order_id" field.
func (u *LotteryCouponUpsertBulk) SetUsedOrderID(v string) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetUsedOrderID(v)
	})
}

// UpdateUsedOrderID sets the "used_order_id" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateUsedOrderID() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateUsedOrderID()
	})
}

// ClearUsedOrderID clears the value of the "used_order_id" field.
func (u *LotteryCouponUpsertBulk) ClearUsedOrderID() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.ClearUsedOrderID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *LotteryCouponUpsertBulk) SetExpiresAt(v time.Time) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateExpiresAt() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetReminded sets the "reminded" field.
func (u *LotteryCouponUpsertBulk) SetReminded(v bool) *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.SetReminded(v)
	})
}

// UpdateReminded sets the "reminded" field to the value that was provided on create.
func (u *LotteryCouponUpsertBulk) UpdateReminded() *LotteryCouponUpsertBulk {
	return u.Update(func(s *LotteryCouponUpsert) {
		s.UpdateReminded()
	})
}

// Exec executes the query.
func (u *LotteryCouponUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryCouponCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCouponCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCouponUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
