// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryparticipant"
)

// LotteryParticipantCreate is the builder for creating a LotteryParticipant entity.
type LotteryParticipantCreate struct {
	config
	mutation *LotteryParticipantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityID sets the "activity_id" field.
func (_c *LotteryParticipantCreate) SetActivityID(v int64) *LotteryParticipantCreate {
	_c.mutation.SetActivityID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LotteryParticipantCreate) SetUserID(v int64) *LotteryParticipantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUserCategory sets the "user_category" field.
func (_c *LotteryParticipantCreate) SetUserCategory(v string) *LotteryParticipantCreate {
	_c.mutation.SetUserCategory(v)
	return _c
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (_c *LotteryParticipantCreate) SetWeightMultiplier(v float64) *LotteryParticipantCreate {
	_c.mutation.SetWeightMultiplier(v)
	return _c
}

// SetNillableWeightMultiplier sets the "weight_multiplier" field if the given value is not nil.
func (_c *LotteryParticipantCreate) SetNillableWeightMultiplier(v *float64) *LotteryParticipantCreate {
	if v != nil {
		_c.SetWeightMultiplier(*v)
	}
	return _c
}

// SetIsWinner sets the "is_winner" field.
func (_c *LotteryParticipantCreate) SetIsWinner(v bool) *LotteryParticipantCreate {
	_c.mutation.SetIsWinner(v)
	return _c
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_c *LotteryParticipantCreate) SetNillableIsWinner(v *bool) *LotteryParticipantCreate {
	if v != nil {
		_c.SetIsWinner(*v)
	}
	return _c
}

// SetCouponID sets the "coupon_id" field.
func (_c *LotteryParticipantCreate) SetCouponID(v int64) *LotteryParticipantCreate {
	_c.mutation.SetCouponID(v)
	return _c
}

// SetNillableCouponID sets the "coupon_id" field if the given value is not nil.
func (_c *LotteryParticipantCreate) SetNillableCouponID(v *int64) *LotteryParticipantCreate {
	if v != nil {
		_c.SetCouponID(*v)
	}
	return _c
}

// SetParticipatedAt sets the "participated_at" field.
func (_c *LotteryParticipantCreate) SetParticipatedAt(v time.Time) *LotteryParticipantCreate {
	_c.mutation.SetParticipatedAt(v)
	return _c
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_c *LotteryParticipantCreate) SetNillableParticipatedAt(v *time.Time) *LotteryParticipantCreate {
	if v != nil {
		_c.SetParticipatedAt(*v)
	}
	return _c
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_c *LotteryParticipantCreate) SetActivity(v *LotteryActivity) *LotteryParticipantCreate {
	return _c.SetActivityID(v.ID)
}

// Mutation returns the LotteryParticipantMutation object of the builder.
func (_c *LotteryParticipantCreate) Mutation() *LotteryParticipantMutation {
	return _c.mutation
}

// Save creates the LotteryParticipant in the database.
func (_c *LotteryParticipantCreate) Save(ctx context.Context) (*LotteryParticipant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryParticipantCreate) SaveX(ctx context.Context) *LotteryParticipant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryParticipantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryParticipantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryParticipantCreate) defaults() {
	if _, ok := _c.mutation.WeightMultiplier(); !ok {
		v := lotteryparticipant.DefaultWeightMultiplier
		_c.mutation.SetWeightMultiplier(v)
	}
	if _, ok := _c.mutation.ParticipatedAt(); !ok {
		v := lotteryparticipant.DefaultParticipatedAt()
		_c.mutation.SetParticipatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryParticipantCreate) check() error {
	if _, ok := _c.mutation.ActivityID(); !ok {
		return &ValidationError{Name: "activity_id", err: errors.New(`ent: missing required field "LotteryParticipant.activity_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LotteryParticipant.user_id"`)}
	}
	if _, ok := _c.mutation.UserCategory(); !ok {
		return &ValidationError{Name: "user_category", err: errors.New(`ent: missing required field "LotteryParticipant.user_category"`)}
	}
	if v, ok := _c.mutation.UserCategory(); ok {
		if err := lotteryparticipant.UserCategoryValidator(v); err != nil {
			return &ValidationError{Name: "user_category", err: fmt.Errorf(`ent: validator failed for field "LotteryParticipant.user_category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WeightMultiplier(); !ok {
		return &ValidationError{Name: "weight_multiplier", err: errors.New(`ent: missing required field "LotteryParticipant.weight_multiplier"`)}
	}
	if _, ok := _c.mutation.ParticipatedAt(); !ok {
		return &ValidationError{Name: "participated_at", err: errors.New(`ent: missing required field "LotteryParticipant.participated_at"`)}
	}
	if len(_c.mutation.ActivityIDs()) == 0 {
		return &ValidationError{Name: "activity", err: errors.New(`ent: missing required edge "LotteryParticipant.activity"`)}
	}
	return nil
}

func (_c *LotteryParticipantCreate) sqlSave(ctx context.Context) (*LotteryParticipant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryParticipantCreate) createSpec() (*LotteryParticipant, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryParticipant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryparticipant.Table, sqlgraph.NewFieldSpec(lotteryparticipant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(lotteryparticipant.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.UserCategory(); ok {
		_spec.SetField(lotteryparticipant.FieldUserCategory, field.TypeString, value)
		_node.UserCategory = value
	}
	if value, ok := _c.mutation.WeightMultiplier(); ok {
		_spec.SetField(lotteryparticipant.FieldWeightMultiplier, field.TypeFloat64, value)
		_node.WeightMultiplier = value
	}
	if value, ok := _c.mutation.IsWinner(); ok {
		_spec.SetField(lotteryparticipant.FieldIsWinner, field.TypeBool, value)
		_node.IsWinner = &value
	}
	if value, ok := _c.mutation.CouponID(); ok {
		_spec.SetField(lotteryparticipant.FieldCouponID, field.TypeInt64, value)
		_node.CouponID = &value
	}
	if value, ok := _c.mutation.ParticipatedAt(); ok {
		_spec.SetField(lotteryparticipant.FieldParticipatedAt, field.TypeTime, value)
		_node.ParticipatedAt = value
	}
	if nodes := _c.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryparticipant.ActivityTable,
			Columns: []string{lotteryparticipant.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryParticipant.Create().
//		SetActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryParticipantUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryParticipantCreate) OnConflict(opts ...sql.ConflictOption) *LotteryParticipantUpsertOne {
	_c.conflict = opts
	return &LotteryParticipantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryParticipantCreate) OnConflictColumns(columns ...string) *LotteryParticipantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryParticipantUpsertOne{
		create: _c,
	}
}

type (
	// LotteryParticipantUpsertOne is the builder for "upsert"-ing
	//  one LotteryParticipant node.
	LotteryParticipantUpsertOne struct {
		create *LotteryParticipantCreate
	}

	// LotteryParticipantUpsert is the "OnConflict" setter.
	LotteryParticipantUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityID sets the "activity_id" field.
func (u *LotteryParticipantUpsert) SetActivityID(v int64) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldActivityID, v)
	return u
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateActivityID() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldActivityID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LotteryParticipantUpsert) SetUserID(v int64) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateUserID() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryParticipantUpsert) AddUserID(v int64) *LotteryParticipantUpsert {
	u.Add(lotteryparticipant.FieldUserID, v)
	return u
}

// SetUserCategory sets the "user_category" field.
func (u *LotteryParticipantUpsert) SetUserCategory(v string) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldUserCategory, v)
	return u
}

// UpdateUserCategory sets the "user_category" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateUserCategory() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldUserCategory)
	return u
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (u *LotteryParticipantUpsert) SetWeightMultiplier(v float64) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldWeightMultiplier, v)
	return u
}

// UpdateWeightMultiplier sets the "weight_multiplier" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateWeightMultiplier() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldWeightMultiplier)
	return u
}

// AddWeightMultiplier adds v to the "weight_multiplier" field.
func (u *LotteryParticipantUpsert) AddWeightMultiplier(v float64) *LotteryParticipantUpsert {
	u.Add(lotteryparticipant.FieldWeightMultiplier, v)
	return u
}

// SetIsWinner sets the "is_winner" field.
func (u *LotteryParticipantUpsert) SetIsWinner(v bool) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldIsWinner, v)
	return u
}

// UpdateIsWinner sets the "is_winner" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateIsWinner() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldIsWinner)
	return u
}

// ClearIsWinner clears the value of the "is_winner" field.
func (u *LotteryParticipantUpsert) ClearIsWinner() *LotteryParticipantUpsert {
	u.SetNull(lotteryparticipant.FieldIsWinner)
	return u
}

// SetCouponID sets the "coupon_id" field.
func (u *LotteryParticipantUpsert) SetCouponID(v int64) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldCouponID, v)
	return u
}

// UpdateCouponID sets the "coupon_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateCouponID() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldCouponID)
	return u
}

// AddCouponID adds v to the "coupon_id" field.
func (u *LotteryParticipantUpsert) AddCouponID(v int64) *LotteryParticipantUpsert {
	u.Add(lotteryparticipant.FieldCouponID, v)
	return u
}

// ClearCouponID clears the value of the "coupon_id" field.
func (u *LotteryParticipantUpsert) ClearCouponID() *LotteryParticipantUpsert {
	u.SetNull(lotteryparticipant.FieldCouponID)
	return u
}

// SetParticipatedAt sets the "participated_at" field.
func (u *LotteryParticipantUpsert) SetParticipatedAt(v time.Time) *LotteryParticipantUpsert {
	u.Set(lotteryparticipant.FieldParticipatedAt, v)
	return u
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *LotteryParticipantUpsert) UpdateParticipatedAt() *LotteryParticipantUpsert {
	u.SetExcluded(lotteryparticipant.FieldParticipatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryParticipantUpsertOne) UpdateNewValues() *LotteryParticipantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryParticipantUpsertOne) Ignore() *LotteryParticipantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryParticipantUpsertOne) DoNothing() *LotteryParticipantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryParticipantCreate.OnConflict
// documentation for more info.
func (u *LotteryParticipantUpsertOne) Update(set func(*LotteryParticipantUpsert)) *LotteryParticipantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryParticipantUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryParticipantUpsertOne) SetActivityID(v int64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateActivityID() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryParticipantUpsertOne) SetUserID(v int64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryParticipantUpsertOne) AddUserID(v int64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateUserID() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateUserID()
	})
}

// SetUserCategory sets the "user_category" field.
func (u *LotteryParticipantUpsertOne) SetUserCategory(v string) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetUserCategory(v)
	})
}

// UpdateUserCategory sets the "user_category" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateUserCategory() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateUserCategory()
	})
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (u *LotteryParticipantUpsertOne) SetWeightMultiplier(v float64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetWeightMultiplier(v)
	})
}

// AddWeightMultiplier adds v to the "weight_multiplier" field.
func (u *LotteryParticipantUpsertOne) AddWeightMultiplier(v float64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddWeightMultiplier(v)
	})
}

// UpdateWeightMultiplier sets the "weight_multiplier" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateWeightMultiplier() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateWeightMultiplier()
	})
}

// SetIsWinner sets the "is_winner" field.
func (u *LotteryParticipantUpsertOne) SetIsWinner(v bool) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetIsWinner(v)
	})
}

// UpdateIsWinner sets the "is_winner" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateIsWinner() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateIsWinner()
	})
}

// ClearIsWinner clears the value of the "is_winner" field.
func (u *LotteryParticipantUpsertOne) ClearIsWinner() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.ClearIsWinner()
	})
}

// SetCouponID sets the "coupon_id" field.
func (u *LotteryParticipantUpsertOne) SetCouponID(v int64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetCouponID(v)
	})
}

// AddCouponID adds v to the "coupon_id" field.
func (u *LotteryParticipantUpsertOne) AddCouponID(v int64) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddCouponID(v)
	})
}

// UpdateCouponID sets the "coupon_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateCouponID() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateCouponID()
	})
}

// ClearCouponID clears the value of the "coupon_id" field.
func (u *LotteryParticipantUpsertOne) ClearCouponID() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.ClearCouponID()
	})
}

// SetParticipatedAt sets the "participated_at" field.
func (u *LotteryParticipantUpsertOne) SetParticipatedAt(v time.Time) *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetParticipatedAt(v)
	})
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *LotteryParticipantUpsertOne) UpdateParticipatedAt() *LotteryParticipantUpsertOne {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateParticipatedAt()
	})
}

// Exec executes the query.
func (u *LotteryParticipantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryParticipantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryParticipantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryParticipantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryParticipantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryParticipantCreateBulk is the builder for creating many LotteryParticipant entities in bulk.
type LotteryParticipantCreateBulk struct {
	config
	err      error
	builders []*LotteryParticipantCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryParticipant entities in the database.
func (_c *LotteryParticipantCreateBulk) Save(ctx context.Context) ([]*LotteryParticipant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryParticipant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryParticipantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryParticipantCreateBulk) SaveX(ctx context.Context) []*LotteryParticipant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryParticipantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryParticipantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryParticipant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryParticipantUpsert) {
//			SetActivityID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryParticipantCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryParticipantUpsertBulk {
	_c.conflict = opts
	return &LotteryParticipantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryParticipantCreateBulk) OnConflictColumns(columns ...string) *LotteryParticipantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryParticipantUpsertBulk{
		create: _c,
	}
}

// LotteryParticipantUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryParticipant nodes.
type LotteryParticipantUpsertBulk struct {
	create *LotteryParticipantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryParticipantUpsertBulk) UpdateNewValues() *LotteryParticipantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryParticipant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryParticipantUpsertBulk) Ignore() *LotteryParticipantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryParticipantUpsertBulk) DoNothing() *LotteryParticipantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryParticipantCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryParticipantUpsertBulk) Update(set func(*LotteryParticipantUpsert)) *LotteryParticipantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryParticipantUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityID sets the "activity_id" field.
func (u *LotteryParticipantUpsertBulk) SetActivityID(v int64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetActivityID(v)
	})
}

// UpdateActivityID sets the "activity_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateActivityID() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateActivityID()
	})
}

// SetUserID sets the "user_id" field.
func (u *LotteryParticipantUpsertBulk) SetUserID(v int64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *LotteryParticipantUpsertBulk) AddUserID(v int64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateUserID() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateUserID()
	})
}

// SetUserCategory sets the "user_category" field.
func (u *LotteryParticipantUpsertBulk) SetUserCategory(v string) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetUserCategory(v)
	})
}

// UpdateUserCategory sets the "user_category" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateUserCategory() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateUserCategory()
	})
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (u *LotteryParticipantUpsertBulk) SetWeightMultiplier(v float64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetWeightMultiplier(v)
	})
}

// AddWeightMultiplier adds v to the "weight_multiplier" field.
func (u *LotteryParticipantUpsertBulk) AddWeightMultiplier(v float64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddWeightMultiplier(v)
	})
}

// UpdateWeightMultiplier sets the "weight_multiplier" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateWeightMultiplier() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateWeightMultiplier()
	})
}

// SetIsWinner sets the "is_winner" field.
func (u *LotteryParticipantUpsertBulk) SetIsWinner(v bool) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetIsWinner(v)
	})
}

// UpdateIsWinner sets the "is_winner" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateIsWinner() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateIsWinner()
	})
}

// ClearIsWinner clears the value of the "is_winner" field.
func (u *LotteryParticipantUpsertBulk) ClearIsWinner() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.ClearIsWinner()
	})
}

// SetCouponID sets the "coupon_id" field.
func (u *LotteryParticipantUpsertBulk) SetCouponID(v int64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetCouponID(v)
	})
}

// AddCouponID adds v to the "coupon_id" field.
func (u *LotteryParticipantUpsertBulk) AddCouponID(v int64) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.AddCouponID(v)
	})
}

// UpdateCouponID sets the "coupon_id" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateCouponID() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateCouponID()
	})
}

// ClearCouponID clears the value of the "coupon_id" field.
func (u *LotteryParticipantUpsertBulk) ClearCouponID() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.ClearCouponID()
	})
}

// SetParticipatedAt sets the "participated_at" field.
func (u *LotteryParticipantUpsertBulk) SetParticipatedAt(v time.Time) *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.SetParticipatedAt(v)
	})
}

// UpdateParticipatedAt sets the "participated_at" field to the value that was provided on create.
func (u *LotteryParticipantUpsertBulk) UpdateParticipatedAt() *LotteryParticipantUpsertBulk {
	return u.Update(func(s *LotteryParticipantUpsert) {
		s.UpdateParticipatedAt()
	})
}

// Exec executes the query.
func (u *LotteryParticipantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryParticipantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryParticipantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryParticipantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
