// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotterycoupon"
	"github.com/Wei-Shaw/sub2api/ent/lotteryparticipant"
)

// LotteryActivityCreate is the builder for creating a LotteryActivity entity.
type LotteryActivityCreate struct {
	config
	mutation *LotteryActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *LotteryActivityCreate) SetTitle(v string) *LotteryActivityCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *LotteryActivityCreate) SetDescription(v string) *LotteryActivityCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableDescription(v *string) *LotteryActivityCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetShareCode sets the "share_code" field.
func (_c *LotteryActivityCreate) SetShareCode(v string) *LotteryActivityCreate {
	_c.mutation.SetShareCode(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryActivityCreate) SetStatus(v string) *LotteryActivityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableStatus(v *string) *LotteryActivityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDrawAt sets the "draw_at" field.
func (_c *LotteryActivityCreate) SetDrawAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetDrawAt(v)
	return _c
}

// SetActivityStartAt sets the "activity_start_at" field.
func (_c *LotteryActivityCreate) SetActivityStartAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetActivityStartAt(v)
	return _c
}

// SetNillableActivityStartAt sets the "activity_start_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableActivityStartAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetActivityStartAt(*v)
	}
	return _c
}

// SetActivityEndAt sets the "activity_end_at" field.
func (_c *LotteryActivityCreate) SetActivityEndAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetActivityEndAt(v)
	return _c
}

// SetMinParticipants sets the "min_participants" field.
func (_c *LotteryActivityCreate) SetMinParticipants(v int) *LotteryActivityCreate {
	_c.mutation.SetMinParticipants(v)
	return _c
}

// SetNillableMinParticipants sets the "min_participants" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableMinParticipants(v *int) *LotteryActivityCreate {
	if v != nil {
		_c.SetMinParticipants(*v)
	}
	return _c
}

// SetBaseWinRate sets the "base_win_rate" field.
func (_c *LotteryActivityCreate) SetBaseWinRate(v float64) *LotteryActivityCreate {
	_c.mutation.SetBaseWinRate(v)
	return _c
}

// SetNillableBaseWinRate sets the "base_win_rate" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableBaseWinRate(v *float64) *LotteryActivityCreate {
	if v != nil {
		_c.SetBaseWinRate(*v)
	}
	return _c
}

// SetWeightConfig sets the "weight_config" field.
func (_c *LotteryActivityCreate) SetWeightConfig(v string) *LotteryActivityCreate {
	_c.mutation.SetWeightConfig(v)
	return _c
}

// SetNillableWeightConfig sets the "weight_config" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableWeightConfig(v *string) *LotteryActivityCreate {
	if v != nil {
		_c.SetWeightConfig(*v)
	}
	return _c
}

// SetWinnerDiscountPercent sets the "winner_discount_percent" field.
func (_c *LotteryActivityCreate) SetWinnerDiscountPercent(v int) *LotteryActivityCreate {
	_c.mutation.SetWinnerDiscountPercent(v)
	return _c
}

// SetNillableWinnerDiscountPercent sets the "winner_discount_percent" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableWinnerDiscountPercent(v *int) *LotteryActivityCreate {
	if v != nil {
		_c.SetWinnerDiscountPercent(*v)
	}
	return _c
}

// SetLoserCouponAmount sets the "loser_coupon_amount" field.
func (_c *LotteryActivityCreate) SetLoserCouponAmount(v float64) *LotteryActivityCreate {
	_c.mutation.SetLoserCouponAmount(v)
	return _c
}

// SetNillableLoserCouponAmount sets the "loser_coupon_amount" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableLoserCouponAmount(v *float64) *LotteryActivityCreate {
	if v != nil {
		_c.SetLoserCouponAmount(*v)
	}
	return _c
}

// SetTempGroupID sets the "temp_group_id" field.
func (_c *LotteryActivityCreate) SetTempGroupID(v int64) *LotteryActivityCreate {
	_c.mutation.SetTempGroupID(v)
	return _c
}

// SetNillableTempGroupID sets the "temp_group_id" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableTempGroupID(v *int64) *LotteryActivityCreate {
	if v != nil {
		_c.SetTempGroupID(*v)
	}
	return _c
}

// SetParticipantCount sets the "participant_count" field.
func (_c *LotteryActivityCreate) SetParticipantCount(v int) *LotteryActivityCreate {
	_c.mutation.SetParticipantCount(v)
	return _c
}

// SetNillableParticipantCount sets the "participant_count" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableParticipantCount(v *int) *LotteryActivityCreate {
	if v != nil {
		_c.SetParticipantCount(*v)
	}
	return _c
}

// SetWinnerCount sets the "winner_count" field.
func (_c *LotteryActivityCreate) SetWinnerCount(v int) *LotteryActivityCreate {
	_c.mutation.SetWinnerCount(v)
	return _c
}

// SetNillableWinnerCount sets the "winner_count" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableWinnerCount(v *int) *LotteryActivityCreate {
	if v != nil {
		_c.SetWinnerCount(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *LotteryActivityCreate) SetCreatedBy(v int64) *LotteryActivityCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryActivityCreate) SetCreatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableCreatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryActivityCreate) SetUpdatedAt(v time.Time) *LotteryActivityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryActivityCreate) SetNillableUpdatedAt(v *time.Time) *LotteryActivityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddParticipantIDs adds the "participants" edge to the LotteryParticipant entity by IDs.
func (_c *LotteryActivityCreate) AddParticipantIDs(ids ...int64) *LotteryActivityCreate {
	_c.mutation.AddParticipantIDs(ids...)
	return _c
}

// AddParticipants adds the "participants" edges to the LotteryParticipant entity.
func (_c *LotteryActivityCreate) AddParticipants(v ...*LotteryParticipant) *LotteryActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipantIDs(ids...)
}

// AddCouponIDs adds the "coupons" edge to the LotteryCoupon entity by IDs.
func (_c *LotteryActivityCreate) AddCouponIDs(ids ...int64) *LotteryActivityCreate {
	_c.mutation.AddCouponIDs(ids...)
	return _c
}

// AddCoupons adds the "coupons" edges to the LotteryCoupon entity.
func (_c *LotteryActivityCreate) AddCoupons(v ...*LotteryCoupon) *LotteryActivityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCouponIDs(ids...)
}

// Mutation returns the LotteryActivityMutation object of the builder.
func (_c *LotteryActivityCreate) Mutation() *LotteryActivityMutation {
	return _c.mutation
}

// Save creates the LotteryActivity in the database.
func (_c *LotteryActivityCreate) Save(ctx context.Context) (*LotteryActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryActivityCreate) SaveX(ctx context.Context) *LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryActivityCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotteryactivity.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ActivityStartAt(); !ok {
		v := lotteryactivity.DefaultActivityStartAt()
		_c.mutation.SetActivityStartAt(v)
	}
	if _, ok := _c.mutation.MinParticipants(); !ok {
		v := lotteryactivity.DefaultMinParticipants
		_c.mutation.SetMinParticipants(v)
	}
	if _, ok := _c.mutation.BaseWinRate(); !ok {
		v := lotteryactivity.DefaultBaseWinRate
		_c.mutation.SetBaseWinRate(v)
	}
	if _, ok := _c.mutation.WeightConfig(); !ok {
		v := lotteryactivity.DefaultWeightConfig
		_c.mutation.SetWeightConfig(v)
	}
	if _, ok := _c.mutation.WinnerDiscountPercent(); !ok {
		v := lotteryactivity.DefaultWinnerDiscountPercent
		_c.mutation.SetWinnerDiscountPercent(v)
	}
	if _, ok := _c.mutation.LoserCouponAmount(); !ok {
		v := lotteryactivity.DefaultLoserCouponAmount
		_c.mutation.SetLoserCouponAmount(v)
	}
	if _, ok := _c.mutation.ParticipantCount(); !ok {
		v := lotteryactivity.DefaultParticipantCount
		_c.mutation.SetParticipantCount(v)
	}
	if _, ok := _c.mutation.WinnerCount(); !ok {
		v := lotteryactivity.DefaultWinnerCount
		_c.mutation.SetWinnerCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotteryactivity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotteryactivity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryActivityCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "LotteryActivity.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := lotteryactivity.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShareCode(); !ok {
		return &ValidationError{Name: "share_code", err: errors.New(`ent: missing required field "LotteryActivity.share_code"`)}
	}
	if v, ok := _c.mutation.ShareCode(); ok {
		if err := lotteryactivity.ShareCodeValidator(v); err != nil {
			return &ValidationError{Name: "share_code", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.share_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryActivity.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotteryactivity.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryActivity.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DrawAt(); !ok {
		return &ValidationError{Name: "draw_at", err: errors.New(`ent: missing required field "LotteryActivity.draw_at"`)}
	}
	if _, ok := _c.mutation.ActivityStartAt(); !ok {
		return &ValidationError{Name: "activity_start_at", err: errors.New(`ent: missing required field "LotteryActivity.activity_start_at"`)}
	}
	if _, ok := _c.mutation.ActivityEndAt(); !ok {
		return &ValidationError{Name: "activity_end_at", err: errors.New(`ent: missing required field "LotteryActivity.activity_end_at"`)}
	}
	if _, ok := _c.mutation.MinParticipants(); !ok {
		return &ValidationError{Name: "min_participants", err: errors.New(`ent: missing required field "LotteryActivity.min_participants"`)}
	}
	if _, ok := _c.mutation.BaseWinRate(); !ok {
		return &ValidationError{Name: "base_win_rate", err: errors.New(`ent: missing required field "LotteryActivity.base_win_rate"`)}
	}
	if _, ok := _c.mutation.WeightConfig(); !ok {
		return &ValidationError{Name: "weight_config", err: errors.New(`ent: missing required field "LotteryActivity.weight_config"`)}
	}
	if _, ok := _c.mutation.WinnerDiscountPercent(); !ok {
		return &ValidationError{Name: "winner_discount_percent", err: errors.New(`ent: missing required field "LotteryActivity.winner_discount_percent"`)}
	}
	if _, ok := _c.mutation.LoserCouponAmount(); !ok {
		return &ValidationError{Name: "loser_coupon_amount", err: errors.New(`ent: missing required field "LotteryActivity.loser_coupon_amount"`)}
	}
	if _, ok := _c.mutation.ParticipantCount(); !ok {
		return &ValidationError{Name: "participant_count", err: errors.New(`ent: missing required field "LotteryActivity.participant_count"`)}
	}
	if _, ok := _c.mutation.WinnerCount(); !ok {
		return &ValidationError{Name: "winner_count", err: errors.New(`ent: missing required field "LotteryActivity.winner_count"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "LotteryActivity.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryActivity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryActivity.updated_at"`)}
	}
	return nil
}

func (_c *LotteryActivityCreate) sqlSave(ctx context.Context) (*LotteryActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryActivityCreate) createSpec() (*LotteryActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotteryactivity.Table, sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(lotteryactivity.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(lotteryactivity.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.ShareCode(); ok {
		_spec.SetField(lotteryactivity.FieldShareCode, field.TypeString, value)
		_node.ShareCode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotteryactivity.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DrawAt(); ok {
		_spec.SetField(lotteryactivity.FieldDrawAt, field.TypeTime, value)
		_node.DrawAt = value
	}
	if value, ok := _c.mutation.ActivityStartAt(); ok {
		_spec.SetField(lotteryactivity.FieldActivityStartAt, field.TypeTime, value)
		_node.ActivityStartAt = value
	}
	if value, ok := _c.mutation.ActivityEndAt(); ok {
		_spec.SetField(lotteryactivity.FieldActivityEndAt, field.TypeTime, value)
		_node.ActivityEndAt = value
	}
	if value, ok := _c.mutation.MinParticipants(); ok {
		_spec.SetField(lotteryactivity.FieldMinParticipants, field.TypeInt, value)
		_node.MinParticipants = value
	}
	if value, ok := _c.mutation.BaseWinRate(); ok {
		_spec.SetField(lotteryactivity.FieldBaseWinRate, field.TypeFloat64, value)
		_node.BaseWinRate = value
	}
	if value, ok := _c.mutation.WeightConfig(); ok {
		_spec.SetField(lotteryactivity.FieldWeightConfig, field.TypeString, value)
		_node.WeightConfig = value
	}
	if value, ok := _c.mutation.WinnerDiscountPercent(); ok {
		_spec.SetField(lotteryactivity.FieldWinnerDiscountPercent, field.TypeInt, value)
		_node.WinnerDiscountPercent = value
	}
	if value, ok := _c.mutation.LoserCouponAmount(); ok {
		_spec.SetField(lotteryactivity.FieldLoserCouponAmount, field.TypeFloat64, value)
		_node.LoserCouponAmount = value
	}
	if value, ok := _c.mutation.TempGroupID(); ok {
		_spec.SetField(lotteryactivity.FieldTempGroupID, field.TypeInt64, value)
		_node.TempGroupID = &value
	}
	if value, ok := _c.mutation.ParticipantCount(); ok {
		_spec.SetField(lotteryactivity.FieldParticipantCount, field.TypeInt, value)
		_node.ParticipantCount = value
	}
	if value, ok := _c.mutation.WinnerCount(); ok {
		_spec.SetField(lotteryactivity.FieldWinnerCount, field.TypeInt, value)
		_node.WinnerCount = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(lotteryactivity.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotteryactivity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.ParticipantsTable,
			Columns: []string{lotteryactivity.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryparticipant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CouponsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   lotteryactivity.CouponsTable,
			Columns: []string{lotteryactivity.CouponsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotterycoupon.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryActivity.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryActivityUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryActivityCreate) OnConflict(opts ...sql.ConflictOption) *LotteryActivityUpsertOne {
	_c.conflict = opts
	return &LotteryActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryActivityCreate) OnConflictColumns(columns ...string) *LotteryActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryActivityUpsertOne{
		create: _c,
	}
}

type (
	// LotteryActivityUpsertOne is the builder for "upsert"-ing
	//  one LotteryActivity node.
	LotteryActivityUpsertOne struct {
		create *LotteryActivityCreate
	}

	// LotteryActivityUpsert is the "OnConflict" setter.
	LotteryActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *LotteryActivityUpsert) SetTitle(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateTitle() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *LotteryActivityUpsert) SetDescription(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateDescription() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *LotteryActivityUpsert) ClearDescription() *LotteryActivityUpsert {
	u.SetNull(lotteryactivity.FieldDescription)
	return u
}

// SetShareCode sets the "share_code" field.
func (u *LotteryActivityUpsert) SetShareCode(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldShareCode, v)
	return u
}

// UpdateShareCode sets the "share_code" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateShareCode() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldShareCode)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsert) SetStatus(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateStatus() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldStatus)
	return u
}

// SetDrawAt sets the "draw_at" field.
func (u *LotteryActivityUpsert) SetDrawAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldDrawAt, v)
	return u
}

// UpdateDrawAt sets the "draw_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateDrawAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldDrawAt)
	return u
}

// SetActivityStartAt sets the "activity_start_at" field.
func (u *LotteryActivityUpsert) SetActivityStartAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldActivityStartAt, v)
	return u
}

// UpdateActivityStartAt sets the "activity_start_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateActivityStartAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldActivityStartAt)
	return u
}

// SetActivityEndAt sets the "activity_end_at" field.
func (u *LotteryActivityUpsert) SetActivityEndAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldActivityEndAt, v)
	return u
}

// UpdateActivityEndAt sets the "activity_end_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateActivityEndAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldActivityEndAt)
	return u
}

// SetMinParticipants sets the "min_participants" field.
func (u *LotteryActivityUpsert) SetMinParticipants(v int) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldMinParticipants, v)
	return u
}

// UpdateMinParticipants sets the "min_participants" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateMinParticipants() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldMinParticipants)
	return u
}

// AddMinParticipants adds v to the "min_participants" field.
func (u *LotteryActivityUpsert) AddMinParticipants(v int) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldMinParticipants, v)
	return u
}

// SetBaseWinRate sets the "base_win_rate" field.
func (u *LotteryActivityUpsert) SetBaseWinRate(v float64) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldBaseWinRate, v)
	return u
}

// UpdateBaseWinRate sets the "base_win_rate" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateBaseWinRate() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldBaseWinRate)
	return u
}

// AddBaseWinRate adds v to the "base_win_rate" field.
func (u *LotteryActivityUpsert) AddBaseWinRate(v float64) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldBaseWinRate, v)
	return u
}

// SetWeightConfig sets the "weight_config" field.
func (u *LotteryActivityUpsert) SetWeightConfig(v string) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldWeightConfig, v)
	return u
}

// UpdateWeightConfig sets the "weight_config" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateWeightConfig() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldWeightConfig)
	return u
}

// SetWinnerDiscountPercent sets the "winner_discount_percent" field.
func (u *LotteryActivityUpsert) SetWinnerDiscountPercent(v int) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldWinnerDiscountPercent, v)
	return u
}

// UpdateWinnerDiscountPercent sets the "winner_discount_percent" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateWinnerDiscountPercent() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldWinnerDiscountPercent)
	return u
}

// AddWinnerDiscountPercent adds v to the "winner_discount_percent" field.
func (u *LotteryActivityUpsert) AddWinnerDiscountPercent(v int) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldWinnerDiscountPercent, v)
	return u
}

// SetLoserCouponAmount sets the "loser_coupon_amount" field.
func (u *LotteryActivityUpsert) SetLoserCouponAmount(v float64) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldLoserCouponAmount, v)
	return u
}

// UpdateLoserCouponAmount sets the "loser_coupon_amount" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateLoserCouponAmount() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldLoserCouponAmount)
	return u
}

// AddLoserCouponAmount adds v to the "loser_coupon_amount" field.
func (u *LotteryActivityUpsert) AddLoserCouponAmount(v float64) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldLoserCouponAmount, v)
	return u
}

// SetTempGroupID sets the "temp_group_id" field.
func (u *LotteryActivityUpsert) SetTempGroupID(v int64) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldTempGroupID, v)
	return u
}

// UpdateTempGroupID sets the "temp_group_id" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateTempGroupID() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldTempGroupID)
	return u
}

// AddTempGroupID adds v to the "temp_group_id" field.
func (u *LotteryActivityUpsert) AddTempGroupID(v int64) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldTempGroupID, v)
	return u
}

// ClearTempGroupID clears the value of the "temp_group_id" field.
func (u *LotteryActivityUpsert) ClearTempGroupID() *LotteryActivityUpsert {
	u.SetNull(lotteryactivity.FieldTempGroupID)
	return u
}

// SetParticipantCount sets the "participant_count" field.
func (u *LotteryActivityUpsert) SetParticipantCount(v int) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldParticipantCount, v)
	return u
}

// UpdateParticipantCount sets the "participant_count" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateParticipantCount() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldParticipantCount)
	return u
}

// AddParticipantCount adds v to the "participant_count" field.
func (u *LotteryActivityUpsert) AddParticipantCount(v int) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldParticipantCount, v)
	return u
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryActivityUpsert) SetWinnerCount(v int) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldWinnerCount, v)
	return u
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateWinnerCount() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldWinnerCount)
	return u
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryActivityUpsert) AddWinnerCount(v int) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldWinnerCount, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryActivityUpsert) SetCreatedBy(v int64) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateCreatedBy() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryActivityUpsert) AddCreatedBy(v int64) *LotteryActivityUpsert {
	u.Add(lotteryactivity.FieldCreatedBy, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsert) SetUpdatedAt(v time.Time) *LotteryActivityUpsert {
	u.Set(lotteryactivity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsert) UpdateUpdatedAt() *LotteryActivityUpsert {
	u.SetExcluded(lotteryactivity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryActivityUpsertOne) UpdateNewValues() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotteryactivity.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryActivityUpsertOne) Ignore() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryActivityUpsertOne) DoNothing() *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryActivityCreate.OnConflict
// documentation for more info.
func (u *LotteryActivityUpsertOne) Update(set func(*LotteryActivityUpsert)) *LotteryActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *LotteryActivityUpsertOne) SetTitle(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateTitle() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *LotteryActivityUpsertOne) SetDescription(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateDescription() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LotteryActivityUpsertOne) ClearDescription() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearDescription()
	})
}

// SetShareCode sets the "share_code" field.
func (u *LotteryActivityUpsertOne) SetShareCode(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetShareCode(v)
	})
}

// UpdateShareCode sets the "share_code" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateShareCode() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateShareCode()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsertOne) SetStatus(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateStatus() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetDrawAt sets the "draw_at" field.
func (u *LotteryActivityUpsertOne) SetDrawAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetDrawAt(v)
	})
}

// UpdateDrawAt sets the "draw_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateDrawAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateDrawAt()
	})
}

// SetActivityStartAt sets the "activity_start_at" field.
func (u *LotteryActivityUpsertOne) SetActivityStartAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetActivityStartAt(v)
	})
}

// UpdateActivityStartAt sets the "activity_start_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateActivityStartAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateActivityStartAt()
	})
}

// SetActivityEndAt sets the "activity_end_at" field.
func (u *LotteryActivityUpsertOne) SetActivityEndAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetActivityEndAt(v)
	})
}

// UpdateActivityEndAt sets the "activity_end_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateActivityEndAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateActivityEndAt()
	})
}

// SetMinParticipants sets the "min_participants" field.
func (u *LotteryActivityUpsertOne) SetMinParticipants(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetMinParticipants(v)
	})
}

// AddMinParticipants adds v to the "min_participants" field.
func (u *LotteryActivityUpsertOne) AddMinParticipants(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddMinParticipants(v)
	})
}

// UpdateMinParticipants sets the "min_participants" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateMinParticipants() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateMinParticipants()
	})
}

// SetBaseWinRate sets the "base_win_rate" field.
func (u *LotteryActivityUpsertOne) SetBaseWinRate(v float64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetBaseWinRate(v)
	})
}

// AddBaseWinRate adds v to the "base_win_rate" field.
func (u *LotteryActivityUpsertOne) AddBaseWinRate(v float64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddBaseWinRate(v)
	})
}

// UpdateBaseWinRate sets the "base_win_rate" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateBaseWinRate() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateBaseWinRate()
	})
}

// SetWeightConfig sets the "weight_config" field.
func (u *LotteryActivityUpsertOne) SetWeightConfig(v string) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWeightConfig(v)
	})
}

// UpdateWeightConfig sets the "weight_config" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateWeightConfig() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWeightConfig()
	})
}

// SetWinnerDiscountPercent sets the "winner_discount_percent" field.
func (u *LotteryActivityUpsertOne) SetWinnerDiscountPercent(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWinnerDiscountPercent(v)
	})
}

// AddWinnerDiscountPercent adds v to the "winner_discount_percent" field.
func (u *LotteryActivityUpsertOne) AddWinnerDiscountPercent(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddWinnerDiscountPercent(v)
	})
}

// UpdateWinnerDiscountPercent sets the "winner_discount_percent" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateWinnerDiscountPercent() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWinnerDiscountPercent()
	})
}

// SetLoserCouponAmount sets the "loser_coupon_amount" field.
func (u *LotteryActivityUpsertOne) SetLoserCouponAmount(v float64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetLoserCouponAmount(v)
	})
}

// AddLoserCouponAmount adds v to the "loser_coupon_amount" field.
func (u *LotteryActivityUpsertOne) AddLoserCouponAmount(v float64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddLoserCouponAmount(v)
	})
}

// UpdateLoserCouponAmount sets the "loser_coupon_amount" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateLoserCouponAmount() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateLoserCouponAmount()
	})
}

// SetTempGroupID sets the "temp_group_id" field.
func (u *LotteryActivityUpsertOne) SetTempGroupID(v int64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTempGroupID(v)
	})
}

// AddTempGroupID adds v to the "temp_group_id" field.
func (u *LotteryActivityUpsertOne) AddTempGroupID(v int64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddTempGroupID(v)
	})
}

// UpdateTempGroupID sets the "temp_group_id" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateTempGroupID() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTempGroupID()
	})
}

// ClearTempGroupID clears the value of the "temp_group_id" field.
func (u *LotteryActivityUpsertOne) ClearTempGroupID() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearTempGroupID()
	})
}

// SetParticipantCount sets the "participant_count" field.
func (u *LotteryActivityUpsertOne) SetParticipantCount(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetParticipantCount(v)
	})
}

// AddParticipantCount adds v to the "participant_count" field.
func (u *LotteryActivityUpsertOne) AddParticipantCount(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddParticipantCount(v)
	})
}

// UpdateParticipantCount sets the "participant_count" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateParticipantCount() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateParticipantCount()
	})
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryActivityUpsertOne) SetWinnerCount(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWinnerCount(v)
	})
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryActivityUpsertOne) AddWinnerCount(v int) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddWinnerCount(v)
	})
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateWinnerCount() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWinnerCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryActivityUpsertOne) SetCreatedBy(v int64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryActivityUpsertOne) AddCreatedBy(v int64) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateCreatedBy() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsertOne) SetUpdatedAt(v time.Time) *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertOne) UpdateUpdatedAt() *LotteryActivityUpsertOne {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryActivityUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryActivityUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryActivityCreateBulk is the builder for creating many LotteryActivity entities in bulk.
type LotteryActivityCreateBulk struct {
	config
	err      error
	builders []*LotteryActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryActivity entities in the database.
func (_c *LotteryActivityCreateBulk) Save(ctx context.Context) ([]*LotteryActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) SaveX(ctx context.Context) []*LotteryActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryActivityUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryActivityUpsertBulk {
	_c.conflict = opts
	return &LotteryActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryActivityCreateBulk) OnConflictColumns(columns ...string) *LotteryActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryActivityUpsertBulk{
		create: _c,
	}
}

// LotteryActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryActivity nodes.
type LotteryActivityUpsertBulk struct {
	create *LotteryActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryActivityUpsertBulk) UpdateNewValues() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotteryactivity.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryActivityUpsertBulk) Ignore() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryActivityUpsertBulk) DoNothing() *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryActivityCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryActivityUpsertBulk) Update(set func(*LotteryActivityUpsert)) *LotteryActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *LotteryActivityUpsertBulk) SetTitle(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateTitle() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *LotteryActivityUpsertBulk) SetDescription(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateDescription() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LotteryActivityUpsertBulk) ClearDescription() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearDescription()
	})
}

// SetShareCode sets the "share_code" field.
func (u *LotteryActivityUpsertBulk) SetShareCode(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetShareCode(v)
	})
}

// UpdateShareCode sets the "share_code" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateShareCode() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateShareCode()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryActivityUpsertBulk) SetStatus(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateStatus() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateStatus()
	})
}

// SetDrawAt sets the "draw_at" field.
func (u *LotteryActivityUpsertBulk) SetDrawAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetDrawAt(v)
	})
}

// UpdateDrawAt sets the "draw_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateDrawAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateDrawAt()
	})
}

// SetActivityStartAt sets the "activity_start_at" field.
func (u *LotteryActivityUpsertBulk) SetActivityStartAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetActivityStartAt(v)
	})
}

// UpdateActivityStartAt sets the "activity_start_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateActivityStartAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateActivityStartAt()
	})
}

// SetActivityEndAt sets the "activity_end_at" field.
func (u *LotteryActivityUpsertBulk) SetActivityEndAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetActivityEndAt(v)
	})
}

// UpdateActivityEndAt sets the "activity_end_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateActivityEndAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateActivityEndAt()
	})
}

// SetMinParticipants sets the "min_participants" field.
func (u *LotteryActivityUpsertBulk) SetMinParticipants(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetMinParticipants(v)
	})
}

// AddMinParticipants adds v to the "min_participants" field.
func (u *LotteryActivityUpsertBulk) AddMinParticipants(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddMinParticipants(v)
	})
}

// UpdateMinParticipants sets the "min_participants" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateMinParticipants() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateMinParticipants()
	})
}

// SetBaseWinRate sets the "base_win_rate" field.
func (u *LotteryActivityUpsertBulk) SetBaseWinRate(v float64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetBaseWinRate(v)
	})
}

// AddBaseWinRate adds v to the "base_win_rate" field.
func (u *LotteryActivityUpsertBulk) AddBaseWinRate(v float64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddBaseWinRate(v)
	})
}

// UpdateBaseWinRate sets the "base_win_rate" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateBaseWinRate() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateBaseWinRate()
	})
}

// SetWeightConfig sets the "weight_config" field.
func (u *LotteryActivityUpsertBulk) SetWeightConfig(v string) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWeightConfig(v)
	})
}

// UpdateWeightConfig sets the "weight_config" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateWeightConfig() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWeightConfig()
	})
}

// SetWinnerDiscountPercent sets the "winner_discount_percent" field.
func (u *LotteryActivityUpsertBulk) SetWinnerDiscountPercent(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWinnerDiscountPercent(v)
	})
}

// AddWinnerDiscountPercent adds v to the "winner_discount_percent" field.
func (u *LotteryActivityUpsertBulk) AddWinnerDiscountPercent(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddWinnerDiscountPercent(v)
	})
}

// UpdateWinnerDiscountPercent sets the "winner_discount_percent" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateWinnerDiscountPercent() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWinnerDiscountPercent()
	})
}

// SetLoserCouponAmount sets the "loser_coupon_amount" field.
func (u *LotteryActivityUpsertBulk) SetLoserCouponAmount(v float64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetLoserCouponAmount(v)
	})
}

// AddLoserCouponAmount adds v to the "loser_coupon_amount" field.
func (u *LotteryActivityUpsertBulk) AddLoserCouponAmount(v float64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddLoserCouponAmount(v)
	})
}

// UpdateLoserCouponAmount sets the "loser_coupon_amount" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateLoserCouponAmount() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateLoserCouponAmount()
	})
}

// SetTempGroupID sets the "temp_group_id" field.
func (u *LotteryActivityUpsertBulk) SetTempGroupID(v int64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetTempGroupID(v)
	})
}

// AddTempGroupID adds v to the "temp_group_id" field.
func (u *LotteryActivityUpsertBulk) AddTempGroupID(v int64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddTempGroupID(v)
	})
}

// UpdateTempGroupID sets the "temp_group_id" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateTempGroupID() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateTempGroupID()
	})
}

// ClearTempGroupID clears the value of the "temp_group_id" field.
func (u *LotteryActivityUpsertBulk) ClearTempGroupID() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.ClearTempGroupID()
	})
}

// SetParticipantCount sets the "participant_count" field.
func (u *LotteryActivityUpsertBulk) SetParticipantCount(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetParticipantCount(v)
	})
}

// AddParticipantCount adds v to the "participant_count" field.
func (u *LotteryActivityUpsertBulk) AddParticipantCount(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddParticipantCount(v)
	})
}

// UpdateParticipantCount sets the "participant_count" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateParticipantCount() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateParticipantCount()
	})
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryActivityUpsertBulk) SetWinnerCount(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetWinnerCount(v)
	})
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryActivityUpsertBulk) AddWinnerCount(v int) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddWinnerCount(v)
	})
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateWinnerCount() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateWinnerCount()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryActivityUpsertBulk) SetCreatedBy(v int64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryActivityUpsertBulk) AddCreatedBy(v int64) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateCreatedBy() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryActivityUpsertBulk) SetUpdatedAt(v time.Time) *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryActivityUpsertBulk) UpdateUpdatedAt() *LotteryActivityUpsertBulk {
	return u.Update(func(s *LotteryActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
