// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotteryactivity"
	"github.com/Wei-Shaw/sub2api/ent/lotteryparticipant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryParticipantUpdate is the builder for updating LotteryParticipant entities.
type LotteryParticipantUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryParticipantMutation
}

// Where appends a list predicates to the LotteryParticipantUpdate builder.
func (_u *LotteryParticipantUpdate) Where(ps ...predicate.LotteryParticipant) *LotteryParticipantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryParticipantUpdate) SetActivityID(v int64) *LotteryParticipantUpdate {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableActivityID(v *int64) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryParticipantUpdate) SetUserID(v int64) *LotteryParticipantUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableUserID(v *int64) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryParticipantUpdate) AddUserID(v int64) *LotteryParticipantUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserCategory sets the "user_category" field.
func (_u *LotteryParticipantUpdate) SetUserCategory(v string) *LotteryParticipantUpdate {
	_u.mutation.SetUserCategory(v)
	return _u
}

// SetNillableUserCategory sets the "user_category" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableUserCategory(v *string) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetUserCategory(*v)
	}
	return _u
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (_u *LotteryParticipantUpdate) SetWeightMultiplier(v float64) *LotteryParticipantUpdate {
	_u.mutation.ResetWeightMultiplier()
	_u.mutation.SetWeightMultiplier(v)
	return _u
}

// SetNillableWeightMultiplier sets the "weight_multiplier" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableWeightMultiplier(v *float64) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetWeightMultiplier(*v)
	}
	return _u
}

// AddWeightMultiplier adds value to the "weight_multiplier" field.
func (_u *LotteryParticipantUpdate) AddWeightMultiplier(v float64) *LotteryParticipantUpdate {
	_u.mutation.AddWeightMultiplier(v)
	return _u
}

// SetIsWinner sets the "is_winner" field.
func (_u *LotteryParticipantUpdate) SetIsWinner(v bool) *LotteryParticipantUpdate {
	_u.mutation.SetIsWinner(v)
	return _u
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableIsWinner(v *bool) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetIsWinner(*v)
	}
	return _u
}

// ClearIsWinner clears the value of the "is_winner" field.
func (_u *LotteryParticipantUpdate) ClearIsWinner() *LotteryParticipantUpdate {
	_u.mutation.ClearIsWinner()
	return _u
}

// SetCouponID sets the "coupon_id" field.
func (_u *LotteryParticipantUpdate) SetCouponID(v int64) *LotteryParticipantUpdate {
	_u.mutation.ResetCouponID()
	_u.mutation.SetCouponID(v)
	return _u
}

// SetNillableCouponID sets the "coupon_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableCouponID(v *int64) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetCouponID(*v)
	}
	return _u
}

// AddCouponID adds value to the "coupon_id" field.
func (_u *LotteryParticipantUpdate) AddCouponID(v int64) *LotteryParticipantUpdate {
	_u.mutation.AddCouponID(v)
	return _u
}

// ClearCouponID clears the value of the "coupon_id" field.
func (_u *LotteryParticipantUpdate) ClearCouponID() *LotteryParticipantUpdate {
	_u.mutation.ClearCouponID()
	return _u
}

// SetParticipatedAt sets the "participated_at" field.
func (_u *LotteryParticipantUpdate) SetParticipatedAt(v time.Time) *LotteryParticipantUpdate {
	_u.mutation.SetParticipatedAt(v)
	return _u
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_u *LotteryParticipantUpdate) SetNillableParticipatedAt(v *time.Time) *LotteryParticipantUpdate {
	if v != nil {
		_u.SetParticipatedAt(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryParticipantUpdate) SetActivity(v *LotteryActivity) *LotteryParticipantUpdate {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the LotteryParticipantMutation object of the builder.
func (_u *LotteryParticipantUpdate) Mutation() *LotteryParticipantMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryParticipantUpdate) ClearActivity() *LotteryParticipantUpdate {
	_u.mutation.ClearActivity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryParticipantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryParticipantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryParticipantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryParticipantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryParticipantUpdate) check() error {
	if v, ok := _u.mutation.UserCategory(); ok {
		if err := lotteryparticipant.UserCategoryValidator(v); err != nil {
			return &ValidationError{Name: "user_category", err: fmt.Errorf(`ent: validator failed for field "LotteryParticipant.user_category": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryParticipant.activity"`)
	}
	return nil
}

func (_u *LotteryParticipantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryparticipant.Table, lotteryparticipant.Columns, sqlgraph.NewFieldSpec(lotteryparticipant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryparticipant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryparticipant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserCategory(); ok {
		_spec.SetField(lotteryparticipant.FieldUserCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeightMultiplier(); ok {
		_spec.SetField(lotteryparticipant.FieldWeightMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightMultiplier(); ok {
		_spec.AddField(lotteryparticipant.FieldWeightMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsWinner(); ok {
		_spec.SetField(lotteryparticipant.FieldIsWinner, field.TypeBool, value)
	}
	if _u.mutation.IsWinnerCleared() {
		_spec.ClearField(lotteryparticipant.FieldIsWinner, field.TypeBool)
	}
	if value, ok := _u.mutation.CouponID(); ok {
		_spec.SetField(lotteryparticipant.FieldCouponID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCouponID(); ok {
		_spec.AddField(lotteryparticipant.FieldCouponID, field.TypeInt64, value)
	}
	if _u.mutation.CouponIDCleared() {
		_spec.ClearField(lotteryparticipant.FieldCouponID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParticipatedAt(); ok {
		_spec.SetField(lotteryparticipant.FieldParticipatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryparticipant.ActivityTable,
			Columns: []string{lotteryparticipant.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryparticipant.ActivityTable,
			Columns: []string{lotteryparticipant.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryParticipantUpdateOne is the builder for updating a single LotteryParticipant entity.
type LotteryParticipantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryParticipantMutation
}

// SetActivityID sets the "activity_id" field.
func (_u *LotteryParticipantUpdateOne) SetActivityID(v int64) *LotteryParticipantUpdateOne {
	_u.mutation.SetActivityID(v)
	return _u
}

// SetNillableActivityID sets the "activity_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableActivityID(v *int64) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetActivityID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LotteryParticipantUpdateOne) SetUserID(v int64) *LotteryParticipantUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableUserID(v *int64) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LotteryParticipantUpdateOne) AddUserID(v int64) *LotteryParticipantUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetUserCategory sets the "user_category" field.
func (_u *LotteryParticipantUpdateOne) SetUserCategory(v string) *LotteryParticipantUpdateOne {
	_u.mutation.SetUserCategory(v)
	return _u
}

// SetNillableUserCategory sets the "user_category" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableUserCategory(v *string) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetUserCategory(*v)
	}
	return _u
}

// SetWeightMultiplier sets the "weight_multiplier" field.
func (_u *LotteryParticipantUpdateOne) SetWeightMultiplier(v float64) *LotteryParticipantUpdateOne {
	_u.mutation.ResetWeightMultiplier()
	_u.mutation.SetWeightMultiplier(v)
	return _u
}

// SetNillableWeightMultiplier sets the "weight_multiplier" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableWeightMultiplier(v *float64) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetWeightMultiplier(*v)
	}
	return _u
}

// AddWeightMultiplier adds value to the "weight_multiplier" field.
func (_u *LotteryParticipantUpdateOne) AddWeightMultiplier(v float64) *LotteryParticipantUpdateOne {
	_u.mutation.AddWeightMultiplier(v)
	return _u
}

// SetIsWinner sets the "is_winner" field.
func (_u *LotteryParticipantUpdateOne) SetIsWinner(v bool) *LotteryParticipantUpdateOne {
	_u.mutation.SetIsWinner(v)
	return _u
}

// SetNillableIsWinner sets the "is_winner" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableIsWinner(v *bool) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetIsWinner(*v)
	}
	return _u
}

// ClearIsWinner clears the value of the "is_winner" field.
func (_u *LotteryParticipantUpdateOne) ClearIsWinner() *LotteryParticipantUpdateOne {
	_u.mutation.ClearIsWinner()
	return _u
}

// SetCouponID sets the "coupon_id" field.
func (_u *LotteryParticipantUpdateOne) SetCouponID(v int64) *LotteryParticipantUpdateOne {
	_u.mutation.ResetCouponID()
	_u.mutation.SetCouponID(v)
	return _u
}

// SetNillableCouponID sets the "coupon_id" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableCouponID(v *int64) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetCouponID(*v)
	}
	return _u
}

// AddCouponID adds value to the "coupon_id" field.
func (_u *LotteryParticipantUpdateOne) AddCouponID(v int64) *LotteryParticipantUpdateOne {
	_u.mutation.AddCouponID(v)
	return _u
}

// ClearCouponID clears the value of the "coupon_id" field.
func (_u *LotteryParticipantUpdateOne) ClearCouponID() *LotteryParticipantUpdateOne {
	_u.mutation.ClearCouponID()
	return _u
}

// SetParticipatedAt sets the "participated_at" field.
func (_u *LotteryParticipantUpdateOne) SetParticipatedAt(v time.Time) *LotteryParticipantUpdateOne {
	_u.mutation.SetParticipatedAt(v)
	return _u
}

// SetNillableParticipatedAt sets the "participated_at" field if the given value is not nil.
func (_u *LotteryParticipantUpdateOne) SetNillableParticipatedAt(v *time.Time) *LotteryParticipantUpdateOne {
	if v != nil {
		_u.SetParticipatedAt(*v)
	}
	return _u
}

// SetActivity sets the "activity" edge to the LotteryActivity entity.
func (_u *LotteryParticipantUpdateOne) SetActivity(v *LotteryActivity) *LotteryParticipantUpdateOne {
	return _u.SetActivityID(v.ID)
}

// Mutation returns the LotteryParticipantMutation object of the builder.
func (_u *LotteryParticipantUpdateOne) Mutation() *LotteryParticipantMutation {
	return _u.mutation
}

// ClearActivity clears the "activity" edge to the LotteryActivity entity.
func (_u *LotteryParticipantUpdateOne) ClearActivity() *LotteryParticipantUpdateOne {
	_u.mutation.ClearActivity()
	return _u
}

// Where appends a list predicates to the LotteryParticipantUpdate builder.
func (_u *LotteryParticipantUpdateOne) Where(ps ...predicate.LotteryParticipant) *LotteryParticipantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryParticipantUpdateOne) Select(field string, fields ...string) *LotteryParticipantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryParticipant entity.
func (_u *LotteryParticipantUpdateOne) Save(ctx context.Context) (*LotteryParticipant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryParticipantUpdateOne) SaveX(ctx context.Context) *LotteryParticipant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryParticipantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryParticipantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryParticipantUpdateOne) check() error {
	if v, ok := _u.mutation.UserCategory(); ok {
		if err := lotteryparticipant.UserCategoryValidator(v); err != nil {
			return &ValidationError{Name: "user_category", err: fmt.Errorf(`ent: validator failed for field "LotteryParticipant.user_category": %w`, err)}
		}
	}
	if _u.mutation.ActivityCleared() && len(_u.mutation.ActivityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LotteryParticipant.activity"`)
	}
	return nil
}

func (_u *LotteryParticipantUpdateOne) sqlSave(ctx context.Context) (_node *LotteryParticipant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotteryparticipant.Table, lotteryparticipant.Columns, sqlgraph.NewFieldSpec(lotteryparticipant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryParticipant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotteryparticipant.FieldID)
		for _, f := range fields {
			if !lotteryparticipant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotteryparticipant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(lotteryparticipant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(lotteryparticipant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserCategory(); ok {
		_spec.SetField(lotteryparticipant.FieldUserCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.WeightMultiplier(); ok {
		_spec.SetField(lotteryparticipant.FieldWeightMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeightMultiplier(); ok {
		_spec.AddField(lotteryparticipant.FieldWeightMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsWinner(); ok {
		_spec.SetField(lotteryparticipant.FieldIsWinner, field.TypeBool, value)
	}
	if _u.mutation.IsWinnerCleared() {
		_spec.ClearField(lotteryparticipant.FieldIsWinner, field.TypeBool)
	}
	if value, ok := _u.mutation.CouponID(); ok {
		_spec.SetField(lotteryparticipant.FieldCouponID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCouponID(); ok {
		_spec.AddField(lotteryparticipant.FieldCouponID, field.TypeInt64, value)
	}
	if _u.mutation.CouponIDCleared() {
		_spec.ClearField(lotteryparticipant.FieldCouponID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParticipatedAt(); ok {
		_spec.SetField(lotteryparticipant.FieldParticipatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryparticipant.ActivityTable,
			Columns: []string{lotteryparticipant.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   lotteryparticipant.ActivityTable,
			Columns: []string{lotteryparticipant.ActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lotteryactivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LotteryParticipant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotteryparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
