// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelPricingUpdate is the builder for updating ModelPricing entities.
type ModelPricingUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPricingMutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdate) Where(ps ...predicate.ModelPricing) *ModelPricingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdate) SetUpdatedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelPricingUpdate) SetDeletedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableDeletedAt(v *time.Time) *ModelPricingUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelPricingUpdate) ClearDeletedAt() *ModelPricingUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModelKey sets the "model_key" field.
func (_u *ModelPricingUpdate) SetModelKey(v string) *ModelPricingUpdate {
	_u.mutation.SetModelKey(v)
	return _u
}

// SetNillableModelKey sets the "model_key" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableModelKey(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetModelKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelPricingUpdate) SetDisplayName(v string) *ModelPricingUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableDisplayName(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ModelPricingUpdate) ClearDisplayName() *ModelPricingUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelPricingUpdate) SetInputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableInputPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelPricingUpdate) AddInputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelPricingUpdate) SetOutputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelPricingUpdate) AddOutputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetInputPricePerMillionPriority sets the "input_price_per_million_priority" field.
func (_u *ModelPricingUpdate) SetInputPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.ResetInputPricePerMillionPriority()
	_u.mutation.SetInputPricePerMillionPriority(v)
	return _u
}

// SetNillableInputPricePerMillionPriority sets the "input_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableInputPricePerMillionPriority(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetInputPricePerMillionPriority(*v)
	}
	return _u
}

// AddInputPricePerMillionPriority adds value to the "input_price_per_million_priority" field.
func (_u *ModelPricingUpdate) AddInputPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.AddInputPricePerMillionPriority(v)
	return _u
}

// SetOutputPricePerMillionPriority sets the "output_price_per_million_priority" field.
func (_u *ModelPricingUpdate) SetOutputPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputPricePerMillionPriority()
	_u.mutation.SetOutputPricePerMillionPriority(v)
	return _u
}

// SetNillableOutputPricePerMillionPriority sets the "output_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputPricePerMillionPriority(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputPricePerMillionPriority(*v)
	}
	return _u
}

// AddOutputPricePerMillionPriority adds value to the "output_price_per_million_priority" field.
func (_u *ModelPricingUpdate) AddOutputPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputPricePerMillionPriority(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdate) SetCacheReadPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheReadPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdate) AddCacheReadPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillionPriority sets the "cache_read_price_per_million_priority" field.
func (_u *ModelPricingUpdate) SetCacheReadPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheReadPricePerMillionPriority()
	_u.mutation.SetCacheReadPricePerMillionPriority(v)
	return _u
}

// SetNillableCacheReadPricePerMillionPriority sets the "cache_read_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheReadPricePerMillionPriority(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheReadPricePerMillionPriority(*v)
	}
	return _u
}

// AddCacheReadPricePerMillionPriority adds value to the "cache_read_price_per_million_priority" field.
func (_u *ModelPricingUpdate) AddCacheReadPricePerMillionPriority(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheReadPricePerMillionPriority(v)
	return _u
}

// SetCacheCreationPricePerMillion sets the "cache_creation_price_per_million" field.
func (_u *ModelPricingUpdate) SetCacheCreationPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheCreationPricePerMillion()
	_u.mutation.SetCacheCreationPricePerMillion(v)
	return _u
}

// SetNillableCacheCreationPricePerMillion sets the "cache_creation_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheCreationPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheCreationPricePerMillion(*v)
	}
	return _u
}

// AddCacheCreationPricePerMillion adds value to the "cache_creation_price_per_million" field.
func (_u *ModelPricingUpdate) AddCacheCreationPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheCreationPricePerMillion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelPricingUpdate) SetEnabled(v bool) *ModelPricingUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableEnabled(v *bool) *ModelPricingUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPricingUpdate) SetNote(v string) *ModelPricingUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableNote(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPricingUpdate) ClearNote() *ModelPricingUpdate {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdate) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPricingUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPricingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelpricing.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelpricing.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdate) check() error {
	if v, ok := _u.mutation.ModelKey(); ok {
		if err := modelpricing.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelpricing.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := modelpricing.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.note": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelpricing.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(modelpricing.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelKey(); ok {
		_spec.SetField(modelpricing.FieldModelKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelpricing.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(modelpricing.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InputPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheCreationPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelpricing.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpricing.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpricing.FieldNote, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPricingUpdateOne is the builder for updating a single ModelPricing entity.
type ModelPricingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPricingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdateOne) SetUpdatedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelPricingUpdateOne) SetDeletedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableDeletedAt(v *time.Time) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelPricingUpdateOne) ClearDeletedAt() *ModelPricingUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModelKey sets the "model_key" field.
func (_u *ModelPricingUpdateOne) SetModelKey(v string) *ModelPricingUpdateOne {
	_u.mutation.SetModelKey(v)
	return _u
}

// SetNillableModelKey sets the "model_key" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableModelKey(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetModelKey(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelPricingUpdateOne) SetDisplayName(v string) *ModelPricingUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableDisplayName(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ModelPricingUpdateOne) ClearDisplayName() *ModelPricingUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetInputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableInputPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddInputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetOutputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddOutputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetInputPricePerMillionPriority sets the "input_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) SetInputPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetInputPricePerMillionPriority()
	_u.mutation.SetInputPricePerMillionPriority(v)
	return _u
}

// SetNillableInputPricePerMillionPriority sets the "input_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableInputPricePerMillionPriority(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetInputPricePerMillionPriority(*v)
	}
	return _u
}

// AddInputPricePerMillionPriority adds value to the "input_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) AddInputPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddInputPricePerMillionPriority(v)
	return _u
}

// SetOutputPricePerMillionPriority sets the "output_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) SetOutputPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputPricePerMillionPriority()
	_u.mutation.SetOutputPricePerMillionPriority(v)
	return _u
}

// SetNillableOutputPricePerMillionPriority sets the "output_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputPricePerMillionPriority(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputPricePerMillionPriority(*v)
	}
	return _u
}

// AddOutputPricePerMillionPriority adds value to the "output_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) AddOutputPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputPricePerMillionPriority(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetCacheReadPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheReadPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddCacheReadPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillionPriority sets the "cache_read_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) SetCacheReadPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheReadPricePerMillionPriority()
	_u.mutation.SetCacheReadPricePerMillionPriority(v)
	return _u
}

// SetNillableCacheReadPricePerMillionPriority sets the "cache_read_price_per_million_priority" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheReadPricePerMillionPriority(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheReadPricePerMillionPriority(*v)
	}
	return _u
}

// AddCacheReadPricePerMillionPriority adds value to the "cache_read_price_per_million_priority" field.
func (_u *ModelPricingUpdateOne) AddCacheReadPricePerMillionPriority(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheReadPricePerMillionPriority(v)
	return _u
}

// SetCacheCreationPricePerMillion sets the "cache_creation_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetCacheCreationPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheCreationPricePerMillion()
	_u.mutation.SetCacheCreationPricePerMillion(v)
	return _u
}

// SetNillableCacheCreationPricePerMillion sets the "cache_creation_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheCreationPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheCreationPricePerMillion(*v)
	}
	return _u
}

// AddCacheCreationPricePerMillion adds value to the "cache_creation_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddCacheCreationPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheCreationPricePerMillion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelPricingUpdateOne) SetEnabled(v bool) *ModelPricingUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableEnabled(v *bool) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *ModelPricingUpdateOne) SetNote(v string) *ModelPricingUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableNote(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ModelPricingUpdateOne) ClearNote() *ModelPricingUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdateOne) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdateOne) Where(ps ...predicate.ModelPricing) *ModelPricingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPricingUpdateOne) Select(field string, fields ...string) *ModelPricingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPricing entity.
func (_u *ModelPricingUpdateOne) Save(ctx context.Context) (*ModelPricing, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) SaveX(ctx context.Context) *ModelPricing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPricingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelPricingUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if modelpricing.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized modelpricing.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := modelpricing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelPricingUpdateOne) check() error {
	if v, ok := _u.mutation.ModelKey(); ok {
		if err := modelpricing.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.model_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelpricing.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := modelpricing.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ModelPricing.note": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelPricingUpdateOne) sqlSave(ctx context.Context) (_node *ModelPricing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPricing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpricing.FieldID)
		for _, f := range fields {
			if !modelpricing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelpricing.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(modelpricing.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelKey(); ok {
		_spec.SetField(modelpricing.FieldModelKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelpricing.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(modelpricing.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InputPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillionPriority(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillionPriority(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillionPriority, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheCreationPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheCreationPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheCreationPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelpricing.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(modelpricing.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(modelpricing.FieldNote, field.TypeString)
	}
	_node = &ModelPricing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
