// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentcallback"
)

// PaymentCallbackCreate is the builder for creating a PaymentCallback entity.
type PaymentCallbackCreate struct {
	config
	mutation *PaymentCallbackMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentCallbackCreate) SetCreatedAt(v time.Time) *PaymentCallbackCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableCreatedAt(v *time.Time) *PaymentCallbackCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentCallbackCreate) SetUpdatedAt(v time.Time) *PaymentCallbackCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableUpdatedAt(v *time.Time) *PaymentCallbackCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *PaymentCallbackCreate) SetOrderNo(v string) *PaymentCallbackCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableOrderNo(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetOrderNo(*v)
	}
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *PaymentCallbackCreate) SetPaymentMethod(v string) *PaymentCallbackCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetTransactionID sets the "transaction_id" field.
func (_c *PaymentCallbackCreate) SetTransactionID(v string) *PaymentCallbackCreate {
	_c.mutation.SetTransactionID(v)
	return _c
}

// SetNillableTransactionID sets the "transaction_id" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableTransactionID(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetTransactionID(*v)
	}
	return _c
}

// SetRequestHeaders sets the "request_headers" field.
func (_c *PaymentCallbackCreate) SetRequestHeaders(v string) *PaymentCallbackCreate {
	_c.mutation.SetRequestHeaders(v)
	return _c
}

// SetNillableRequestHeaders sets the "request_headers" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableRequestHeaders(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetRequestHeaders(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *PaymentCallbackCreate) SetRequestBody(v string) *PaymentCallbackCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableRequestBody(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetSignatureValid sets the "signature_valid" field.
func (_c *PaymentCallbackCreate) SetSignatureValid(v bool) *PaymentCallbackCreate {
	_c.mutation.SetSignatureValid(v)
	return _c
}

// SetNillableSignatureValid sets the "signature_valid" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableSignatureValid(v *bool) *PaymentCallbackCreate {
	if v != nil {
		_c.SetSignatureValid(*v)
	}
	return _c
}

// SetProcessStatus sets the "process_status" field.
func (_c *PaymentCallbackCreate) SetProcessStatus(v string) *PaymentCallbackCreate {
	_c.mutation.SetProcessStatus(v)
	return _c
}

// SetNillableProcessStatus sets the "process_status" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableProcessStatus(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetProcessStatus(*v)
	}
	return _c
}

// SetProcessMessage sets the "process_message" field.
func (_c *PaymentCallbackCreate) SetProcessMessage(v string) *PaymentCallbackCreate {
	_c.mutation.SetProcessMessage(v)
	return _c
}

// SetNillableProcessMessage sets the "process_message" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableProcessMessage(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetProcessMessage(*v)
	}
	return _c
}

// SetResponseCode sets the "response_code" field.
func (_c *PaymentCallbackCreate) SetResponseCode(v string) *PaymentCallbackCreate {
	_c.mutation.SetResponseCode(v)
	return _c
}

// SetNillableResponseCode sets the "response_code" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableResponseCode(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetResponseCode(*v)
	}
	return _c
}

// SetResponseMessage sets the "response_message" field.
func (_c *PaymentCallbackCreate) SetResponseMessage(v string) *PaymentCallbackCreate {
	_c.mutation.SetResponseMessage(v)
	return _c
}

// SetNillableResponseMessage sets the "response_message" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableResponseMessage(v *string) *PaymentCallbackCreate {
	if v != nil {
		_c.SetResponseMessage(*v)
	}
	return _c
}

// SetProcessTimeMs sets the "process_time_ms" field.
func (_c *PaymentCallbackCreate) SetProcessTimeMs(v int64) *PaymentCallbackCreate {
	_c.mutation.SetProcessTimeMs(v)
	return _c
}

// SetNillableProcessTimeMs sets the "process_time_ms" field if the given value is not nil.
func (_c *PaymentCallbackCreate) SetNillableProcessTimeMs(v *int64) *PaymentCallbackCreate {
	if v != nil {
		_c.SetProcessTimeMs(*v)
	}
	return _c
}

// Mutation returns the PaymentCallbackMutation object of the builder.
func (_c *PaymentCallbackCreate) Mutation() *PaymentCallbackMutation {
	return _c.mutation
}

// Save creates the PaymentCallback in the database.
func (_c *PaymentCallbackCreate) Save(ctx context.Context) (*PaymentCallback, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCallbackCreate) SaveX(ctx context.Context) *PaymentCallback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCallbackCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCallbackCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCallbackCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentcallback.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentcallback.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		v := paymentcallback.DefaultRequestHeaders
		_c.mutation.SetRequestHeaders(v)
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		v := paymentcallback.DefaultRequestBody
		_c.mutation.SetRequestBody(v)
	}
	if _, ok := _c.mutation.SignatureValid(); !ok {
		v := paymentcallback.DefaultSignatureValid
		_c.mutation.SetSignatureValid(v)
	}
	if _, ok := _c.mutation.ProcessStatus(); !ok {
		v := paymentcallback.DefaultProcessStatus
		_c.mutation.SetProcessStatus(v)
	}
	if _, ok := _c.mutation.ProcessMessage(); !ok {
		v := paymentcallback.DefaultProcessMessage
		_c.mutation.SetProcessMessage(v)
	}
	if _, ok := _c.mutation.ResponseCode(); !ok {
		v := paymentcallback.DefaultResponseCode
		_c.mutation.SetResponseCode(v)
	}
	if _, ok := _c.mutation.ResponseMessage(); !ok {
		v := paymentcallback.DefaultResponseMessage
		_c.mutation.SetResponseMessage(v)
	}
	if _, ok := _c.mutation.ProcessTimeMs(); !ok {
		v := paymentcallback.DefaultProcessTimeMs
		_c.mutation.SetProcessTimeMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCallbackCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentCallback.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentCallback.updated_at"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := paymentcallback.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentCallback.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "PaymentCallback.payment_method"`)}
	}
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := paymentcallback.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentCallback.payment_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TransactionID(); ok {
		if err := paymentcallback.TransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "transaction_id", err: fmt.Errorf(`ent: validator failed for field "PaymentCallback.transaction_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHeaders(); !ok {
		return &ValidationError{Name: "request_headers", err: errors.New(`ent: missing required field "PaymentCallback.request_headers"`)}
	}
	if _, ok := _c.mutation.RequestBody(); !ok {
		return &ValidationError{Name: "request_body", err: errors.New(`ent: missing required field "PaymentCallback.request_body"`)}
	}
	if _, ok := _c.mutation.SignatureValid(); !ok {
		return &ValidationError{Name: "signature_valid", err: errors.New(`ent: missing required field "PaymentCallback.signature_valid"`)}
	}
	if _, ok := _c.mutation.ProcessStatus(); !ok {
		return &ValidationError{Name: "process_status", err: errors.New(`ent: missing required field "PaymentCallback.process_status"`)}
	}
	if v, ok := _c.mutation.ProcessStatus(); ok {
		if err := paymentcallback.ProcessStatusValidator(v); err != nil {
			return &ValidationError{Name: "process_status", err: fmt.Errorf(`ent: validator failed for field "PaymentCallback.process_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProcessMessage(); !ok {
		return &ValidationError{Name: "process_message", err: errors.New(`ent: missing required field "PaymentCallback.process_message"`)}
	}
	if _, ok := _c.mutation.ResponseCode(); !ok {
		return &ValidationError{Name: "response_code", err: errors.New(`ent: missing required field "PaymentCallback.response_code"`)}
	}
	if v, ok := _c.mutation.ResponseCode(); ok {
		if err := paymentcallback.ResponseCodeValidator(v); err != nil {
			return &ValidationError{Name: "response_code", err: fmt.Errorf(`ent: validator failed for field "PaymentCallback.response_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseMessage(); !ok {
		return &ValidationError{Name: "response_message", err: errors.New(`ent: missing required field "PaymentCallback.response_message"`)}
	}
	if _, ok := _c.mutation.ProcessTimeMs(); !ok {
		return &ValidationError{Name: "process_time_ms", err: errors.New(`ent: missing required field "PaymentCallback.process_time_ms"`)}
	}
	return nil
}

func (_c *PaymentCallbackCreate) sqlSave(ctx context.Context) (*PaymentCallback, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCallbackCreate) createSpec() (*PaymentCallback, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentCallback{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentcallback.Table, sqlgraph.NewFieldSpec(paymentcallback.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentcallback.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentcallback.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(paymentcallback.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = &value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(paymentcallback.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.TransactionID(); ok {
		_spec.SetField(paymentcallback.FieldTransactionID, field.TypeString, value)
		_node.TransactionID = &value
	}
	if value, ok := _c.mutation.RequestHeaders(); ok {
		_spec.SetField(paymentcallback.FieldRequestHeaders, field.TypeString, value)
		_node.RequestHeaders = value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(paymentcallback.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = value
	}
	if value, ok := _c.mutation.SignatureValid(); ok {
		_spec.SetField(paymentcallback.FieldSignatureValid, field.TypeBool, value)
		_node.SignatureValid = value
	}
	if value, ok := _c.mutation.ProcessStatus(); ok {
		_spec.SetField(paymentcallback.FieldProcessStatus, field.TypeString, value)
		_node.ProcessStatus = value
	}
	if value, ok := _c.mutation.ProcessMessage(); ok {
		_spec.SetField(paymentcallback.FieldProcessMessage, field.TypeString, value)
		_node.ProcessMessage = value
	}
	if value, ok := _c.mutation.ResponseCode(); ok {
		_spec.SetField(paymentcallback.FieldResponseCode, field.TypeString, value)
		_node.ResponseCode = value
	}
	if value, ok := _c.mutation.ResponseMessage(); ok {
		_spec.SetField(paymentcallback.FieldResponseMessage, field.TypeString, value)
		_node.ResponseMessage = value
	}
	if value, ok := _c.mutation.ProcessTimeMs(); ok {
		_spec.SetField(paymentcallback.FieldProcessTimeMs, field.TypeInt64, value)
		_node.ProcessTimeMs = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentCallback.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentCallbackUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentCallbackCreate) OnConflict(opts ...sql.ConflictOption) *PaymentCallbackUpsertOne {
	_c.conflict = opts
	return &PaymentCallbackUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentCallbackCreate) OnConflictColumns(columns ...string) *PaymentCallbackUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentCallbackUpsertOne{
		create: _c,
	}
}

type (
	// PaymentCallbackUpsertOne is the builder for "upsert"-ing
	//  one PaymentCallback node.
	PaymentCallbackUpsertOne struct {
		create *PaymentCallbackCreate
	}

	// PaymentCallbackUpsert is the "OnConflict" setter.
	PaymentCallbackUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentCallbackUpsert) SetUpdatedAt(v time.Time) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateUpdatedAt() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentCallbackUpsert) SetOrderNo(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateOrderNo() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldOrderNo)
	return u
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *PaymentCallbackUpsert) ClearOrderNo() *PaymentCallbackUpsert {
	u.SetNull(paymentcallback.FieldOrderNo)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentCallbackUpsert) SetPaymentMethod(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdatePaymentMethod() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldPaymentMethod)
	return u
}

// SetTransactionID sets the "transaction_id" field.
func (u *PaymentCallbackUpsert) SetTransactionID(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldTransactionID, v)
	return u
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateTransactionID() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldTransactionID)
	return u
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *PaymentCallbackUpsert) ClearTransactionID() *PaymentCallbackUpsert {
	u.SetNull(paymentcallback.FieldTransactionID)
	return u
}

// SetRequestHeaders sets the "request_headers" field.
func (u *PaymentCallbackUpsert) SetRequestHeaders(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldRequestHeaders, v)
	return u
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateRequestHeaders() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldRequestHeaders)
	return u
}

// SetRequestBody sets the "request_body" field.
func (u *PaymentCallbackUpsert) SetRequestBody(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldRequestBody, v)
	return u
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateRequestBody() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldRequestBody)
	return u
}

// SetSignatureValid sets the "signature_valid" field.
func (u *PaymentCallbackUpsert) SetSignatureValid(v bool) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldSignatureValid, v)
	return u
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateSignatureValid() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldSignatureValid)
	return u
}

// SetProcessStatus sets the "process_status" field.
func (u *PaymentCallbackUpsert) SetProcessStatus(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldProcessStatus, v)
	return u
}

// UpdateProcessStatus sets the "process_status" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateProcessStatus() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldProcessStatus)
	return u
}

// SetProcessMessage sets the "process_message" field.
func (u *PaymentCallbackUpsert) SetProcessMessage(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldProcessMessage, v)
	return u
}

// UpdateProcessMessage sets the "process_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateProcessMessage() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldProcessMessage)
	return u
}

// SetResponseCode sets the "response_code" field.
func (u *PaymentCallbackUpsert) SetResponseCode(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldResponseCode, v)
	return u
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateResponseCode() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldResponseCode)
	return u
}

// SetResponseMessage sets the "response_message" field.
func (u *PaymentCallbackUpsert) SetResponseMessage(v string) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldResponseMessage, v)
	return u
}

// UpdateResponseMessage sets the "response_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateResponseMessage() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldResponseMessage)
	return u
}

// SetProcessTimeMs sets the "process_time_ms" field.
func (u *PaymentCallbackUpsert) SetProcessTimeMs(v int64) *PaymentCallbackUpsert {
	u.Set(paymentcallback.FieldProcessTimeMs, v)
	return u
}

// UpdateProcessTimeMs sets the "process_time_ms" field to the value that was provided on create.
func (u *PaymentCallbackUpsert) UpdateProcessTimeMs() *PaymentCallbackUpsert {
	u.SetExcluded(paymentcallback.FieldProcessTimeMs)
	return u
}

// AddProcessTimeMs adds v to the "process_time_ms" field.
func (u *PaymentCallbackUpsert) AddProcessTimeMs(v int64) *PaymentCallbackUpsert {
	u.Add(paymentcallback.FieldProcessTimeMs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentCallbackUpsertOne) UpdateNewValues() *PaymentCallbackUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentcallback.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentCallbackUpsertOne) Ignore() *PaymentCallbackUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentCallbackUpsertOne) DoNothing() *PaymentCallbackUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentCallbackCreate.OnConflict
// documentation for more info.
func (u *PaymentCallbackUpsertOne) Update(set func(*PaymentCallbackUpsert)) *PaymentCallbackUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentCallbackUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentCallbackUpsertOne) SetUpdatedAt(v time.Time) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateUpdatedAt() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentCallbackUpsertOne) SetOrderNo(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateOrderNo() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *PaymentCallbackUpsertOne) ClearOrderNo() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.ClearOrderNo()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentCallbackUpsertOne) SetPaymentMethod(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdatePaymentMethod() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *PaymentCallbackUpsertOne) SetTransactionID(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateTransactionID() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateTransactionID()
	})
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *PaymentCallbackUpsertOne) ClearTransactionID() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.ClearTransactionID()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *PaymentCallbackUpsertOne) SetRequestHeaders(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateRequestHeaders() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *PaymentCallbackUpsertOne) SetRequestBody(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateRequestBody() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateRequestBody()
	})
}

// SetSignatureValid sets the "signature_valid" field.
func (u *PaymentCallbackUpsertOne) SetSignatureValid(v bool) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetSignatureValid(v)
	})
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateSignatureValid() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateSignatureValid()
	})
}

// SetProcessStatus sets the "process_status" field.
func (u *PaymentCallbackUpsertOne) SetProcessStatus(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessStatus(v)
	})
}

// UpdateProcessStatus sets the "process_status" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateProcessStatus() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessStatus()
	})
}

// SetProcessMessage sets the "process_message" field.
func (u *PaymentCallbackUpsertOne) SetProcessMessage(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessMessage(v)
	})
}

// UpdateProcessMessage sets the "process_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateProcessMessage() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessMessage()
	})
}

// SetResponseCode sets the "response_code" field.
func (u *PaymentCallbackUpsertOne) SetResponseCode(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetResponseCode(v)
	})
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateResponseCode() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateResponseCode()
	})
}

// SetResponseMessage sets the "response_message" field.
func (u *PaymentCallbackUpsertOne) SetResponseMessage(v string) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetResponseMessage(v)
	})
}

// UpdateResponseMessage sets the "response_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateResponseMessage() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateResponseMessage()
	})
}

// SetProcessTimeMs sets the "process_time_ms" field.
func (u *PaymentCallbackUpsertOne) SetProcessTimeMs(v int64) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessTimeMs(v)
	})
}

// AddProcessTimeMs adds v to the "process_time_ms" field.
func (u *PaymentCallbackUpsertOne) AddProcessTimeMs(v int64) *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.AddProcessTimeMs(v)
	})
}

// UpdateProcessTimeMs sets the "process_time_ms" field to the value that was provided on create.
func (u *PaymentCallbackUpsertOne) UpdateProcessTimeMs() *PaymentCallbackUpsertOne {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessTimeMs()
	})
}

// Exec executes the query.
func (u *PaymentCallbackUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentCallbackCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentCallbackUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentCallbackUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentCallbackUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentCallbackCreateBulk is the builder for creating many PaymentCallback entities in bulk.
type PaymentCallbackCreateBulk struct {
	config
	err      error
	builders []*PaymentCallbackCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentCallback entities in the database.
func (_c *PaymentCallbackCreateBulk) Save(ctx context.Context) ([]*PaymentCallback, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentCallback, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentCallbackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCallbackCreateBulk) SaveX(ctx context.Context) []*PaymentCallback {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCallbackCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCallbackCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentCallback.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentCallbackUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentCallbackCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentCallbackUpsertBulk {
	_c.conflict = opts
	return &PaymentCallbackUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentCallbackCreateBulk) OnConflictColumns(columns ...string) *PaymentCallbackUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentCallbackUpsertBulk{
		create: _c,
	}
}

// PaymentCallbackUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentCallback nodes.
type PaymentCallbackUpsertBulk struct {
	create *PaymentCallbackCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentCallbackUpsertBulk) UpdateNewValues() *PaymentCallbackUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentcallback.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentCallback.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentCallbackUpsertBulk) Ignore() *PaymentCallbackUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentCallbackUpsertBulk) DoNothing() *PaymentCallbackUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentCallbackCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentCallbackUpsertBulk) Update(set func(*PaymentCallbackUpsert)) *PaymentCallbackUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentCallbackUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentCallbackUpsertBulk) SetUpdatedAt(v time.Time) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateUpdatedAt() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentCallbackUpsertBulk) SetOrderNo(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateOrderNo() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateOrderNo()
	})
}

// ClearOrderNo clears the value of the "order_no" field.
func (u *PaymentCallbackUpsertBulk) ClearOrderNo() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.ClearOrderNo()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *PaymentCallbackUpsertBulk) SetPaymentMethod(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdatePaymentMethod() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetTransactionID sets the "transaction_id" field.
func (u *PaymentCallbackUpsertBulk) SetTransactionID(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetTransactionID(v)
	})
}

// UpdateTransactionID sets the "transaction_id" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateTransactionID() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateTransactionID()
	})
}

// ClearTransactionID clears the value of the "transaction_id" field.
func (u *PaymentCallbackUpsertBulk) ClearTransactionID() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.ClearTransactionID()
	})
}

// SetRequestHeaders sets the "request_headers" field.
func (u *PaymentCallbackUpsertBulk) SetRequestHeaders(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetRequestHeaders(v)
	})
}

// UpdateRequestHeaders sets the "request_headers" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateRequestHeaders() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateRequestHeaders()
	})
}

// SetRequestBody sets the "request_body" field.
func (u *PaymentCallbackUpsertBulk) SetRequestBody(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetRequestBody(v)
	})
}

// UpdateRequestBody sets the "request_body" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateRequestBody() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateRequestBody()
	})
}

// SetSignatureValid sets the "signature_valid" field.
func (u *PaymentCallbackUpsertBulk) SetSignatureValid(v bool) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetSignatureValid(v)
	})
}

// UpdateSignatureValid sets the "signature_valid" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateSignatureValid() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateSignatureValid()
	})
}

// SetProcessStatus sets the "process_status" field.
func (u *PaymentCallbackUpsertBulk) SetProcessStatus(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessStatus(v)
	})
}

// UpdateProcessStatus sets the "process_status" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateProcessStatus() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessStatus()
	})
}

// SetProcessMessage sets the "process_message" field.
func (u *PaymentCallbackUpsertBulk) SetProcessMessage(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessMessage(v)
	})
}

// UpdateProcessMessage sets the "process_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateProcessMessage() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessMessage()
	})
}

// SetResponseCode sets the "response_code" field.
func (u *PaymentCallbackUpsertBulk) SetResponseCode(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetResponseCode(v)
	})
}

// UpdateResponseCode sets the "response_code" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateResponseCode() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateResponseCode()
	})
}

// SetResponseMessage sets the "response_message" field.
func (u *PaymentCallbackUpsertBulk) SetResponseMessage(v string) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetResponseMessage(v)
	})
}

// UpdateResponseMessage sets the "response_message" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateResponseMessage() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateResponseMessage()
	})
}

// SetProcessTimeMs sets the "process_time_ms" field.
func (u *PaymentCallbackUpsertBulk) SetProcessTimeMs(v int64) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.SetProcessTimeMs(v)
	})
}

// AddProcessTimeMs adds v to the "process_time_ms" field.
func (u *PaymentCallbackUpsertBulk) AddProcessTimeMs(v int64) *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.AddProcessTimeMs(v)
	})
}

// UpdateProcessTimeMs sets the "process_time_ms" field to the value that was provided on create.
func (u *PaymentCallbackUpsertBulk) UpdateProcessTimeMs() *PaymentCallbackUpsertBulk {
	return u.Update(func(s *PaymentCallbackUpsert) {
		s.UpdateProcessTimeMs()
	})
}

// Exec executes the query.
func (u *PaymentCallbackUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentCallbackCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentCallbackCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentCallbackUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
