// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/rechargeorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RechargeOrderCreate is the builder for creating a RechargeOrder entity.
type RechargeOrderCreate struct {
	config
	mutation *RechargeOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeOrderCreate) SetCreatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableCreatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeOrderCreate) SetUpdatedAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableUpdatedAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *RechargeOrderCreate) SetOrderNo(v string) *RechargeOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RechargeOrderCreate) SetUserID(v int64) *RechargeOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RechargeOrderCreate) SetAmount(v float64) *RechargeOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *RechargeOrderCreate) SetPaymentMethod(v string) *RechargeOrderCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetPaymentChannel sets the "payment_channel" field.
func (_c *RechargeOrderCreate) SetPaymentChannel(v string) *RechargeOrderCreate {
	_c.mutation.SetPaymentChannel(v)
	return _c
}

// SetNillablePaymentChannel sets the "payment_channel" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaymentChannel(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaymentChannel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RechargeOrderCreate) SetStatus(v string) *RechargeOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableStatus(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (_c *RechargeOrderCreate) SetWechatTransactionID(v string) *RechargeOrderCreate {
	_c.mutation.SetWechatTransactionID(v)
	return _c
}

// SetNillableWechatTransactionID sets the "wechat_transaction_id" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableWechatTransactionID(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetWechatTransactionID(*v)
	}
	return _c
}

// SetQrcodeURL sets the "qrcode_url" field.
func (_c *RechargeOrderCreate) SetQrcodeURL(v string) *RechargeOrderCreate {
	_c.mutation.SetQrcodeURL(v)
	return _c
}

// SetNillableQrcodeURL sets the "qrcode_url" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableQrcodeURL(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetQrcodeURL(*v)
	}
	return _c
}

// SetPrepayID sets the "prepay_id" field.
func (_c *RechargeOrderCreate) SetPrepayID(v string) *RechargeOrderCreate {
	_c.mutation.SetPrepayID(v)
	return _c
}

// SetNillablePrepayID sets the "prepay_id" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePrepayID(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetPrepayID(*v)
	}
	return _c
}

// SetExpireAt sets the "expire_at" field.
func (_c *RechargeOrderCreate) SetExpireAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetExpireAt(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *RechargeOrderCreate) SetPaidAt(v time.Time) *RechargeOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillablePaidAt(v *time.Time) *RechargeOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RechargeOrderCreate) SetNotes(v string) *RechargeOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RechargeOrderCreate) SetNillableNotes(v *string) *RechargeOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RechargeOrderCreate) SetUser(v *User) *RechargeOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RechargeOrderMutation object of the builder.
func (_c *RechargeOrderCreate) Mutation() *RechargeOrderMutation {
	return _c.mutation
}

// Save creates the RechargeOrder in the database.
func (_c *RechargeOrderCreate) Save(ctx context.Context) (*RechargeOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeOrderCreate) SaveX(ctx context.Context) *RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargeorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargeorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.PaymentChannel(); !ok {
		v := rechargeorder.DefaultPaymentChannel
		_c.mutation.SetPaymentChannel(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rechargeorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := rechargeorder.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "RechargeOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := rechargeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RechargeOrder.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := rechargeorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RechargeOrder.amount"`)}
	}
	if v, ok := _c.mutation.Amount(); ok {
		if err := rechargeorder.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "RechargeOrder.payment_method"`)}
	}
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := rechargeorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.payment_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentChannel(); !ok {
		return &ValidationError{Name: "payment_channel", err: errors.New(`ent: missing required field "RechargeOrder.payment_channel"`)}
	}
	if v, ok := _c.mutation.PaymentChannel(); ok {
		if err := rechargeorder.PaymentChannelValidator(v); err != nil {
			return &ValidationError{Name: "payment_channel", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.payment_channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RechargeOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rechargeorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WechatTransactionID(); ok {
		if err := rechargeorder.WechatTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wechat_transaction_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.wechat_transaction_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PrepayID(); ok {
		if err := rechargeorder.PrepayIDValidator(v); err != nil {
			return &ValidationError{Name: "prepay_id", err: fmt.Errorf(`ent: validator failed for field "RechargeOrder.prepay_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpireAt(); !ok {
		return &ValidationError{Name: "expire_at", err: errors.New(`ent: missing required field "RechargeOrder.expire_at"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "RechargeOrder.notes"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RechargeOrder.user"`)}
	}
	return nil
}

func (_c *RechargeOrderCreate) sqlSave(ctx context.Context) (*RechargeOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeOrderCreate) createSpec() (*RechargeOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargeorder.Table, sqlgraph.NewFieldSpec(rechargeorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(rechargeorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rechargeorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(rechargeorder.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.PaymentChannel(); ok {
		_spec.SetField(rechargeorder.FieldPaymentChannel, field.TypeString, value)
		_node.PaymentChannel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rechargeorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.WechatTransactionID(); ok {
		_spec.SetField(rechargeorder.FieldWechatTransactionID, field.TypeString, value)
		_node.WechatTransactionID = &value
	}
	if value, ok := _c.mutation.QrcodeURL(); ok {
		_spec.SetField(rechargeorder.FieldQrcodeURL, field.TypeString, value)
		_node.QrcodeURL = &value
	}
	if value, ok := _c.mutation.PrepayID(); ok {
		_spec.SetField(rechargeorder.FieldPrepayID, field.TypeString, value)
		_node.PrepayID = &value
	}
	if value, ok := _c.mutation.ExpireAt(); ok {
		_spec.SetField(rechargeorder.FieldExpireAt, field.TypeTime, value)
		_node.ExpireAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(rechargeorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(rechargeorder.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargeorder.UserTable,
			Columns: []string{rechargeorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertOne {
	_c.conflict = opts
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreate) OnConflictColumns(columns ...string) *RechargeOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertOne{
		create: _c,
	}
}

type (
	// RechargeOrderUpsertOne is the builder for "upsert"-ing
	//  one RechargeOrder node.
	RechargeOrderUpsertOne struct {
		create *RechargeOrderCreate
	}

	// RechargeOrderUpsert is the "OnConflict" setter.
	RechargeOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsert) SetUpdatedAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUpdatedAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUpdatedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsert) SetOrderNo(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateOrderNo() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsert) SetUserID(v int64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateUserID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsert) SetAmount(v float64) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateAmount() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsert) AddAmount(v float64) *RechargeOrderUpsert {
	u.Add(rechargeorder.FieldAmount, v)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsert) SetPaymentMethod(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaymentMethod() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaymentMethod)
	return u
}

// SetPaymentChannel sets the "payment_channel" field.
func (u *RechargeOrderUpsert) SetPaymentChannel(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaymentChannel, v)
	return u
}

// UpdatePaymentChannel sets the "payment_channel" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaymentChannel() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaymentChannel)
	return u
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsert) SetStatus(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateStatus() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldStatus)
	return u
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *RechargeOrderUpsert) SetWechatTransactionID(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldWechatTransactionID, v)
	return u
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateWechatTransactionID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldWechatTransactionID)
	return u
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *RechargeOrderUpsert) ClearWechatTransactionID() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldWechatTransactionID)
	return u
}

// SetQrcodeURL sets the "qrcode_url" field.
func (u *RechargeOrderUpsert) SetQrcodeURL(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldQrcodeURL, v)
	return u
}

// UpdateQrcodeURL sets the "qrcode_url" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateQrcodeURL() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldQrcodeURL)
	return u
}

// ClearQrcodeURL clears the value of the "qrcode_url" field.
func (u *RechargeOrderUpsert) ClearQrcodeURL() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldQrcodeURL)
	return u
}

// SetPrepayID sets the "prepay_id" field.
func (u *RechargeOrderUpsert) SetPrepayID(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPrepayID, v)
	return u
}

// UpdatePrepayID sets the "prepay_id" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePrepayID() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPrepayID)
	return u
}

// ClearPrepayID clears the value of the "prepay_id" field.
func (u *RechargeOrderUpsert) ClearPrepayID() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPrepayID)
	return u
}

// SetExpireAt sets the "expire_at" field.
func (u *RechargeOrderUpsert) SetExpireAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldExpireAt, v)
	return u
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateExpireAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldExpireAt)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsert) SetPaidAt(v time.Time) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdatePaidAt() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsert) ClearPaidAt() *RechargeOrderUpsert {
	u.SetNull(rechargeorder.FieldPaidAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsert) SetNotes(v string) *RechargeOrderUpsert {
	u.Set(rechargeorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsert) UpdateNotes() *RechargeOrderUpsert {
	u.SetExcluded(rechargeorder.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertOne) UpdateNewValues() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargeorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeOrderUpsertOne) Ignore() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertOne) DoNothing() *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreate.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertOne) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertOne) SetUpdatedAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUpdatedAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsertOne) SetOrderNo(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateOrderNo() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertOne) SetUserID(v int64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateUserID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertOne) SetAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertOne) AddAmount(v float64) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateAmount() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsertOne) SetPaymentMethod(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaymentMethod() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentChannel sets the "payment_channel" field.
func (u *RechargeOrderUpsertOne) SetPaymentChannel(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentChannel(v)
	})
}

// UpdatePaymentChannel sets the "payment_channel" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaymentChannel() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentChannel()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertOne) SetStatus(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateStatus() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *RechargeOrderUpsertOne) SetWechatTransactionID(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetWechatTransactionID(v)
	})
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateWechatTransactionID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateWechatTransactionID()
	})
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *RechargeOrderUpsertOne) ClearWechatTransactionID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearWechatTransactionID()
	})
}

// SetQrcodeURL sets the "qrcode_url" field.
func (u *RechargeOrderUpsertOne) SetQrcodeURL(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetQrcodeURL(v)
	})
}

// UpdateQrcodeURL sets the "qrcode_url" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateQrcodeURL() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateQrcodeURL()
	})
}

// ClearQrcodeURL clears the value of the "qrcode_url" field.
func (u *RechargeOrderUpsertOne) ClearQrcodeURL() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearQrcodeURL()
	})
}

// SetPrepayID sets the "prepay_id" field.
func (u *RechargeOrderUpsertOne) SetPrepayID(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPrepayID(v)
	})
}

// UpdatePrepayID sets the "prepay_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePrepayID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePrepayID()
	})
}

// ClearPrepayID clears the value of the "prepay_id" field.
func (u *RechargeOrderUpsertOne) ClearPrepayID() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPrepayID()
	})
}

// SetExpireAt sets the "expire_at" field.
func (u *RechargeOrderUpsertOne) SetExpireAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExpireAt(v)
	})
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateExpireAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExpireAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertOne) SetPaidAt(v time.Time) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdatePaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertOne) ClearPaidAt() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsertOne) SetNotes(v string) *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsertOne) UpdateNotes() *RechargeOrderUpsertOne {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeOrderCreateBulk is the builder for creating many RechargeOrder entities in bulk.
type RechargeOrderCreateBulk struct {
	config
	err      error
	builders []*RechargeOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeOrder entities in the database.
func (_c *RechargeOrderCreateBulk) Save(ctx context.Context) ([]*RechargeOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) SaveX(ctx context.Context) []*RechargeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeOrderUpsertBulk {
	_c.conflict = opts
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeOrderCreateBulk) OnConflictColumns(columns ...string) *RechargeOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeOrderUpsertBulk{
		create: _c,
	}
}

// RechargeOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeOrder nodes.
type RechargeOrderUpsertBulk struct {
	create *RechargeOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) UpdateNewValues() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargeorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeOrderUpsertBulk) Ignore() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeOrderUpsertBulk) DoNothing() *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeOrderCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeOrderUpsertBulk) Update(set func(*RechargeOrderUpsert)) *RechargeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeOrderUpsertBulk) SetUpdatedAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUpdatedAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *RechargeOrderUpsertBulk) SetOrderNo(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateOrderNo() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeOrderUpsertBulk) SetUserID(v int64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateUserID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeOrderUpsertBulk) SetAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeOrderUpsertBulk) AddAmount(v float64) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateAmount() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *RechargeOrderUpsertBulk) SetPaymentMethod(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaymentMethod() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentChannel sets the "payment_channel" field.
func (u *RechargeOrderUpsertBulk) SetPaymentChannel(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaymentChannel(v)
	})
}

// UpdatePaymentChannel sets the "payment_channel" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaymentChannel() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaymentChannel()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeOrderUpsertBulk) SetStatus(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateStatus() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetWechatTransactionID sets the "wechat_transaction_id" field.
func (u *RechargeOrderUpsertBulk) SetWechatTransactionID(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetWechatTransactionID(v)
	})
}

// UpdateWechatTransactionID sets the "wechat_transaction_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateWechatTransactionID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateWechatTransactionID()
	})
}

// ClearWechatTransactionID clears the value of the "wechat_transaction_id" field.
func (u *RechargeOrderUpsertBulk) ClearWechatTransactionID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearWechatTransactionID()
	})
}

// SetQrcodeURL sets the "qrcode_url" field.
func (u *RechargeOrderUpsertBulk) SetQrcodeURL(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetQrcodeURL(v)
	})
}

// UpdateQrcodeURL sets the "qrcode_url" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateQrcodeURL() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateQrcodeURL()
	})
}

// ClearQrcodeURL clears the value of the "qrcode_url" field.
func (u *RechargeOrderUpsertBulk) ClearQrcodeURL() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearQrcodeURL()
	})
}

// SetPrepayID sets the "prepay_id" field.
func (u *RechargeOrderUpsertBulk) SetPrepayID(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPrepayID(v)
	})
}

// UpdatePrepayID sets the "prepay_id" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePrepayID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePrepayID()
	})
}

// ClearPrepayID clears the value of the "prepay_id" field.
func (u *RechargeOrderUpsertBulk) ClearPrepayID() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPrepayID()
	})
}

// SetExpireAt sets the "expire_at" field.
func (u *RechargeOrderUpsertBulk) SetExpireAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetExpireAt(v)
	})
}

// UpdateExpireAt sets the "expire_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateExpireAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateExpireAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *RechargeOrderUpsertBulk) SetPaidAt(v time.Time) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdatePaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *RechargeOrderUpsertBulk) ClearPaidAt() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetNotes sets the "notes" field.
func (u *RechargeOrderUpsertBulk) SetNotes(v string) *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RechargeOrderUpsertBulk) UpdateNotes() *RechargeOrderUpsertBulk {
	return u.Update(func(s *RechargeOrderUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *RechargeOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
