// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userreferralprofile"
)

// UserReferralProfileUpdate is the builder for updating UserReferralProfile entities.
type UserReferralProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserReferralProfileMutation
}

// Where appends a list predicates to the UserReferralProfileUpdate builder.
func (_u *UserReferralProfileUpdate) Where(ps ...predicate.UserReferralProfile) *UserReferralProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserReferralProfileUpdate) SetUserID(v int64) *UserReferralProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserReferralProfileUpdate) SetNillableUserID(v *int64) *UserReferralProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserReferralProfileUpdate) SetReferralCode(v string) *UserReferralProfileUpdate {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserReferralProfileUpdate) SetNillableReferralCode(v *string) *UserReferralProfileUpdate {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserReferralProfileUpdate) SetUser(v *User) *UserReferralProfileUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserReferralProfileMutation object of the builder.
func (_u *UserReferralProfileUpdate) Mutation() *UserReferralProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserReferralProfileUpdate) ClearUser() *UserReferralProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserReferralProfileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserReferralProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserReferralProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserReferralProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserReferralProfileUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userreferralprofile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserReferralProfile.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferralCode(); ok {
		if err := userreferralprofile.ReferralCodeValidator(v); err != nil {
			return &ValidationError{Name: "referral_code", err: fmt.Errorf(`ent: validator failed for field "UserReferralProfile.referral_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserReferralProfile.user"`)
	}
	return nil
}

func (_u *UserReferralProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userreferralprofile.Table, userreferralprofile.Columns, sqlgraph.NewFieldSpec(userreferralprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(userreferralprofile.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferralprofile.UserTable,
			Columns: []string{userreferralprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferralprofile.UserTable,
			Columns: []string{userreferralprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreferralprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserReferralProfileUpdateOne is the builder for updating a single UserReferralProfile entity.
type UserReferralProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserReferralProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserReferralProfileUpdateOne) SetUserID(v int64) *UserReferralProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserReferralProfileUpdateOne) SetNillableUserID(v *int64) *UserReferralProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetReferralCode sets the "referral_code" field.
func (_u *UserReferralProfileUpdateOne) SetReferralCode(v string) *UserReferralProfileUpdateOne {
	_u.mutation.SetReferralCode(v)
	return _u
}

// SetNillableReferralCode sets the "referral_code" field if the given value is not nil.
func (_u *UserReferralProfileUpdateOne) SetNillableReferralCode(v *string) *UserReferralProfileUpdateOne {
	if v != nil {
		_u.SetReferralCode(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserReferralProfileUpdateOne) SetUser(v *User) *UserReferralProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserReferralProfileMutation object of the builder.
func (_u *UserReferralProfileUpdateOne) Mutation() *UserReferralProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserReferralProfileUpdateOne) ClearUser() *UserReferralProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserReferralProfileUpdate builder.
func (_u *UserReferralProfileUpdateOne) Where(ps ...predicate.UserReferralProfile) *UserReferralProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserReferralProfileUpdateOne) Select(field string, fields ...string) *UserReferralProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserReferralProfile entity.
func (_u *UserReferralProfileUpdateOne) Save(ctx context.Context) (*UserReferralProfile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserReferralProfileUpdateOne) SaveX(ctx context.Context) *UserReferralProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserReferralProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserReferralProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserReferralProfileUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userreferralprofile.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserReferralProfile.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReferralCode(); ok {
		if err := userreferralprofile.ReferralCodeValidator(v); err != nil {
			return &ValidationError{Name: "referral_code", err: fmt.Errorf(`ent: validator failed for field "UserReferralProfile.referral_code": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserReferralProfile.user"`)
	}
	return nil
}

func (_u *UserReferralProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserReferralProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userreferralprofile.Table, userreferralprofile.Columns, sqlgraph.NewFieldSpec(userreferralprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserReferralProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userreferralprofile.FieldID)
		for _, f := range fields {
			if !userreferralprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userreferralprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReferralCode(); ok {
		_spec.SetField(userreferralprofile.FieldReferralCode, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferralprofile.UserTable,
			Columns: []string{userreferralprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferralprofile.UserTable,
			Columns: []string{userreferralprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserReferralProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreferralprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
