// Code generated by ent, DO NOT EDIT.

package lotterycoupon

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldID, id))
}

// ActivityID applies equality check predicate on the "activity_id" field. It's identical to ActivityIDEQ.
func ActivityID(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldActivityID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUserID, v))
}

// CouponType applies equality check predicate on the "coupon_type" field. It's identical to CouponTypeEQ.
func CouponType(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldCouponType, v))
}

// DiscountPercent applies equality check predicate on the "discount_percent" field. It's identical to DiscountPercentEQ.
func DiscountPercent(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldDiscountPercent, v))
}

// ReductionAmount applies equality check predicate on the "reduction_amount" field. It's identical to ReductionAmountEQ.
func ReductionAmount(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldReductionAmount, v))
}

// ApplicableScope applies equality check predicate on the "applicable_scope" field. It's identical to ApplicableScopeEQ.
func ApplicableScope(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldApplicableScope, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldStatus, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUsedAt, v))
}

// UsedOrderID applies equality check predicate on the "used_order_id" field. It's identical to UsedOrderIDEQ.
func UsedOrderID(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUsedOrderID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldExpiresAt, v))
}

// Reminded applies equality check predicate on the "reminded" field. It's identical to RemindedEQ.
func Reminded(v bool) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldReminded, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// ActivityIDEQ applies the EQ predicate on the "activity_id" field.
func ActivityIDEQ(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldActivityID, v))
}

// ActivityIDNEQ applies the NEQ predicate on the "activity_id" field.
func ActivityIDNEQ(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldActivityID, v))
}

// ActivityIDIn applies the In predicate on the "activity_id" field.
func ActivityIDIn(vs ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldActivityID, vs...))
}

// ActivityIDNotIn applies the NotIn predicate on the "activity_id" field.
func ActivityIDNotIn(vs ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldActivityID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldUserID, v))
}

// CouponTypeEQ applies the EQ predicate on the "coupon_type" field.
func CouponTypeEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldCouponType, v))
}

// CouponTypeNEQ applies the NEQ predicate on the "coupon_type" field.
func CouponTypeNEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldCouponType, v))
}

// CouponTypeIn applies the In predicate on the "coupon_type" field.
func CouponTypeIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldCouponType, vs...))
}

// CouponTypeNotIn applies the NotIn predicate on the "coupon_type" field.
func CouponTypeNotIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldCouponType, vs...))
}

// CouponTypeGT applies the GT predicate on the "coupon_type" field.
func CouponTypeGT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldCouponType, v))
}

// CouponTypeGTE applies the GTE predicate on the "coupon_type" field.
func CouponTypeGTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldCouponType, v))
}

// CouponTypeLT applies the LT predicate on the "coupon_type" field.
func CouponTypeLT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldCouponType, v))
}

// CouponTypeLTE applies the LTE predicate on the "coupon_type" field.
func CouponTypeLTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldCouponType, v))
}

// CouponTypeContains applies the Contains predicate on the "coupon_type" field.
func CouponTypeContains(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContains(FieldCouponType, v))
}

// CouponTypeHasPrefix applies the HasPrefix predicate on the "coupon_type" field.
func CouponTypeHasPrefix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasPrefix(FieldCouponType, v))
}

// CouponTypeHasSuffix applies the HasSuffix predicate on the "coupon_type" field.
func CouponTypeHasSuffix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasSuffix(FieldCouponType, v))
}

// CouponTypeEqualFold applies the EqualFold predicate on the "coupon_type" field.
func CouponTypeEqualFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEqualFold(FieldCouponType, v))
}

// CouponTypeContainsFold applies the ContainsFold predicate on the "coupon_type" field.
func CouponTypeContainsFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContainsFold(FieldCouponType, v))
}

// DiscountPercentEQ applies the EQ predicate on the "discount_percent" field.
func DiscountPercentEQ(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldDiscountPercent, v))
}

// DiscountPercentNEQ applies the NEQ predicate on the "discount_percent" field.
func DiscountPercentNEQ(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldDiscountPercent, v))
}

// DiscountPercentIn applies the In predicate on the "discount_percent" field.
func DiscountPercentIn(vs ...int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldDiscountPercent, vs...))
}

// DiscountPercentNotIn applies the NotIn predicate on the "discount_percent" field.
func DiscountPercentNotIn(vs ...int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldDiscountPercent, vs...))
}

// DiscountPercentGT applies the GT predicate on the "discount_percent" field.
func DiscountPercentGT(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldDiscountPercent, v))
}

// DiscountPercentGTE applies the GTE predicate on the "discount_percent" field.
func DiscountPercentGTE(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldDiscountPercent, v))
}

// DiscountPercentLT applies the LT predicate on the "discount_percent" field.
func DiscountPercentLT(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldDiscountPercent, v))
}

// DiscountPercentLTE applies the LTE predicate on the "discount_percent" field.
func DiscountPercentLTE(v int) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldDiscountPercent, v))
}

// DiscountPercentIsNil applies the IsNil predicate on the "discount_percent" field.
func DiscountPercentIsNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIsNull(FieldDiscountPercent))
}

// DiscountPercentNotNil applies the NotNil predicate on the "discount_percent" field.
func DiscountPercentNotNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotNull(FieldDiscountPercent))
}

// ReductionAmountEQ applies the EQ predicate on the "reduction_amount" field.
func ReductionAmountEQ(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldReductionAmount, v))
}

// ReductionAmountNEQ applies the NEQ predicate on the "reduction_amount" field.
func ReductionAmountNEQ(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldReductionAmount, v))
}

// ReductionAmountIn applies the In predicate on the "reduction_amount" field.
func ReductionAmountIn(vs ...float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldReductionAmount, vs...))
}

// ReductionAmountNotIn applies the NotIn predicate on the "reduction_amount" field.
func ReductionAmountNotIn(vs ...float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldReductionAmount, vs...))
}

// ReductionAmountGT applies the GT predicate on the "reduction_amount" field.
func ReductionAmountGT(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldReductionAmount, v))
}

// ReductionAmountGTE applies the GTE predicate on the "reduction_amount" field.
func ReductionAmountGTE(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldReductionAmount, v))
}

// ReductionAmountLT applies the LT predicate on the "reduction_amount" field.
func ReductionAmountLT(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldReductionAmount, v))
}

// ReductionAmountLTE applies the LTE predicate on the "reduction_amount" field.
func ReductionAmountLTE(v float64) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldReductionAmount, v))
}

// ReductionAmountIsNil applies the IsNil predicate on the "reduction_amount" field.
func ReductionAmountIsNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIsNull(FieldReductionAmount))
}

// ReductionAmountNotNil applies the NotNil predicate on the "reduction_amount" field.
func ReductionAmountNotNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotNull(FieldReductionAmount))
}

// ApplicableScopeEQ applies the EQ predicate on the "applicable_scope" field.
func ApplicableScopeEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldApplicableScope, v))
}

// ApplicableScopeNEQ applies the NEQ predicate on the "applicable_scope" field.
func ApplicableScopeNEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldApplicableScope, v))
}

// ApplicableScopeIn applies the In predicate on the "applicable_scope" field.
func ApplicableScopeIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldApplicableScope, vs...))
}

// ApplicableScopeNotIn applies the NotIn predicate on the "applicable_scope" field.
func ApplicableScopeNotIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldApplicableScope, vs...))
}

// ApplicableScopeGT applies the GT predicate on the "applicable_scope" field.
func ApplicableScopeGT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldApplicableScope, v))
}

// ApplicableScopeGTE applies the GTE predicate on the "applicable_scope" field.
func ApplicableScopeGTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldApplicableScope, v))
}

// ApplicableScopeLT applies the LT predicate on the "applicable_scope" field.
func ApplicableScopeLT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldApplicableScope, v))
}

// ApplicableScopeLTE applies the LTE predicate on the "applicable_scope" field.
func ApplicableScopeLTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldApplicableScope, v))
}

// ApplicableScopeContains applies the Contains predicate on the "applicable_scope" field.
func ApplicableScopeContains(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContains(FieldApplicableScope, v))
}

// ApplicableScopeHasPrefix applies the HasPrefix predicate on the "applicable_scope" field.
func ApplicableScopeHasPrefix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasPrefix(FieldApplicableScope, v))
}

// ApplicableScopeHasSuffix applies the HasSuffix predicate on the "applicable_scope" field.
func ApplicableScopeHasSuffix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasSuffix(FieldApplicableScope, v))
}

// ApplicableScopeEqualFold applies the EqualFold predicate on the "applicable_scope" field.
func ApplicableScopeEqualFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEqualFold(FieldApplicableScope, v))
}

// ApplicableScopeContainsFold applies the ContainsFold predicate on the "applicable_scope" field.
func ApplicableScopeContainsFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContainsFold(FieldApplicableScope, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContainsFold(FieldStatus, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotNull(FieldUsedAt))
}

// UsedOrderIDEQ applies the EQ predicate on the "used_order_id" field.
func UsedOrderIDEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldUsedOrderID, v))
}

// UsedOrderIDNEQ applies the NEQ predicate on the "used_order_id" field.
func UsedOrderIDNEQ(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldUsedOrderID, v))
}

// UsedOrderIDIn applies the In predicate on the "used_order_id" field.
func UsedOrderIDIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldUsedOrderID, vs...))
}

// UsedOrderIDNotIn applies the NotIn predicate on the "used_order_id" field.
func UsedOrderIDNotIn(vs ...string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldUsedOrderID, vs...))
}

// UsedOrderIDGT applies the GT predicate on the "used_order_id" field.
func UsedOrderIDGT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldUsedOrderID, v))
}

// UsedOrderIDGTE applies the GTE predicate on the "used_order_id" field.
func UsedOrderIDGTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldUsedOrderID, v))
}

// UsedOrderIDLT applies the LT predicate on the "used_order_id" field.
func UsedOrderIDLT(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldUsedOrderID, v))
}

// UsedOrderIDLTE applies the LTE predicate on the "used_order_id" field.
func UsedOrderIDLTE(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldUsedOrderID, v))
}

// UsedOrderIDContains applies the Contains predicate on the "used_order_id" field.
func UsedOrderIDContains(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContains(FieldUsedOrderID, v))
}

// UsedOrderIDHasPrefix applies the HasPrefix predicate on the "used_order_id" field.
func UsedOrderIDHasPrefix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasPrefix(FieldUsedOrderID, v))
}

// UsedOrderIDHasSuffix applies the HasSuffix predicate on the "used_order_id" field.
func UsedOrderIDHasSuffix(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldHasSuffix(FieldUsedOrderID, v))
}

// UsedOrderIDIsNil applies the IsNil predicate on the "used_order_id" field.
func UsedOrderIDIsNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIsNull(FieldUsedOrderID))
}

// UsedOrderIDNotNil applies the NotNil predicate on the "used_order_id" field.
func UsedOrderIDNotNil() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotNull(FieldUsedOrderID))
}

// UsedOrderIDEqualFold applies the EqualFold predicate on the "used_order_id" field.
func UsedOrderIDEqualFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEqualFold(FieldUsedOrderID, v))
}

// UsedOrderIDContainsFold applies the ContainsFold predicate on the "used_order_id" field.
func UsedOrderIDContainsFold(v string) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldContainsFold(FieldUsedOrderID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldExpiresAt, v))
}

// RemindedEQ applies the EQ predicate on the "reminded" field.
func RemindedEQ(v bool) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldReminded, v))
}

// RemindedNEQ applies the NEQ predicate on the "reminded" field.
func RemindedNEQ(v bool) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldReminded, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.FieldLTE(FieldCreatedAt, v))
}

// HasActivity applies the HasEdge predicate on the "activity" edge.
func HasActivity() predicate.LotteryCoupon {
	return predicate.LotteryCoupon(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ActivityTable, ActivityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActivityWith applies the HasEdge predicate on the "activity" edge with a given conditions (other predicates).
func HasActivityWith(preds ...predicate.LotteryActivity) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(func(s *sql.Selector) {
		step := newActivityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryCoupon) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryCoupon) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryCoupon) predicate.LotteryCoupon {
	return predicate.LotteryCoupon(sql.NotPredicates(p))
}
